### ISSUE TITLE
401 HTTP Basic Authentication pop-up support

### ISSUE THREAD

**Issue by eeble** [limpkin/mooltipass#109]
I have a few sites I need to log into that use 401 Auth popups to log in (such as corporate email).  It would be great if we could handle those as well with the mooltipass.
(Thanks to Josh for finding the link, it looks like it might be possible to handle http auth popups with chrome): http://stackoverflow.com/questions/3902411/avoid-http-auth-popup-in-a-chrome-extension-digest

**Comment by limpkin** [comment]
hey there... for me this has been solved... can you confirm?
