### ISSUE TITLE
Incorporate port numbers into credentials

### ISSUE THREAD

**Issue by eeble** [limpkin/mooltipass#110]
If you have a site with multiple distinct sites that only differ in port number, the mooltipass currently tries to apply the credentials it knows for the base address (minus port number).
for instance: http://example.com/site1 might be different from https://example.com:12345/site2, but the mooltipass currently only stores based on 'example.com'

**Comment by limpkin** [comment]
eeble: does your use case really exist? I don't think i've ever encountered something like that...

**Comment by limpkin** [comment]
ip address detection implemented, port numbers discredited (for now) but could be added later on if there's a lot of demand :).
Also in case a given website might change port numbers...

**Comment by teamyamaha91** [comment]
i would use this!

On Sat, May 16, 2015 at 1:35 PM, Mathieu <notifications@github.com> wrote:

> ip address detection implemented, port numbers discredited (for now) but
> could be added later on if there's a lot of demand :).
> Also in case a given website might change port numbers...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/limpkin/mooltipass/issues/110#issuecomment-102657801>.
>



-- 
~Jesse
