### ISSUE TITLE
No way to erase card if MP is erased before card

### ISSUE THREAD

**Issue by jnwatts** [limpkin/mooltipass#121]
Presuming that the user knows the PIN for the card, they should be given the option to create a new user using the card anyways, or the choice to erase the card. Unless modify myself a custom firmware, I have no way to recover this card (thankfully it's not blocked, though it took some low level modification to be sure of that w/o blocking the card).

**Comment by apocsantos** [comment]
Is there any way to flash a locked card ?

**Comment by limpkin** [comment]
if the card is blocked, nothing can be done.

**Comment by apocsantos** [comment]
ok so 3 for garbadge

**Comment by bigbellyburger** [comment]
> added in latest release

How is this accessed?

**Comment by limpkin** [comment]
by going to the advanced tab, accessed using ctrl - shift - f2
