### ISSUE TITLE
HOTP support

### ISSUE THREAD

**Issue by massar** [limpkin/mooltipass#132]
Instead of having to grab the cellphone, get the Google Auth app (or similar) and typing in the number from there, what about HOTP support in mooltipass?

Same checks apply:
 - plug in mooltipass
 - user puts smartcard in
 - types in PIN to unlock
 - browser plugin hints about HOTP, or one selects HOTP from OLED screen
 - select the correct HOTP key (browser plugin could help)
 - current HOTP key + time left is shown, just hit 'yes' or 'no' to send authcode over the keyboard interface
 - presto

This does mean that the mooltipass requires a RTC though, or at least correct time, which it might receive through USB from the host computer. (if time is off then HOTP does not work).

**Comment by limpkin** [comment]
unfortunately.... no space :(
mooltipass v2 hopefully!
