### ISSUE TITLE
basic utf-8 support needed for OLED strings

### ISSUE THREAD

**Issue by harlequin-tech** [limpkin/mooltipass#139]
To support non-ASCII characters like "éàïô", the string functions in OLEDMP will need to handle a subset of the UTF-8 encoded characters and map them onto the 8-bit character range 128-255.

The string "éàïô" is encoded as { 0xc3, 0xa9, 0xc3, 0xa0, 0xc3, 0xaf, 0xc3, 0xb4 }.

**Comment by limpkin** [comment]
upcoming push request with proper input sanitizing:
![img_20150124_213133](https://cloud.githubusercontent.com/assets/6170291/5889038/825bebf6-a414-11e4-91b7-b5fb430d4273.jpg)
