### ISSUE TITLE
Displaying space terminated strings messes with the display, "!" char doesn't exist

### ISSUE THREAD

**Issue by limpkin** [limpkin/mooltipass#141]

**Comment by limpkin** [comment]
@harlequin-tech could you help us with your library?

This is what I get when trying to print  !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

![img_20150118_154052](https://cloud.githubusercontent.com/assets/6170291/5792761/c452fe1e-9f28-11e4-9400-123ead38a1a5.jpg)

**Comment by limpkin** [comment]
finding one of your messages dated more or less year ago... you seemed to already have this bug:

72dpi:
![](https://lh6.googleusercontent.com/-zLPgnw2aUeM/UvyMRgsTZkI/AAAAAAAAACQ/GVjQAJINsIA/s1600/profont_10_72dpi.jpg)

100dpi:
![](https://lh4.googleusercontent.com/-6quOeiQUOug/UvyMVxfA7NI/AAAAAAAAACY/aVMSRUhEPPE/s1600/profont_10_100dpi.jpg)

**Comment by limpkin** [comment]
So unfortunately Josh's push didn't solve the problem.
I managed to get a binary compare match by calling:
font.py -n name -p build/profontiix_regular_10.png -x build/profontiix_regular_10.xml -d 1
in the fonts folder.
The generated font.img file perfectly matches our current 7_font_profont_10.img so at least we're sure how to generate our font file.

**Comment by limpkin** [comment]
looking at profontiix_regular_10.xml we have for the " " char, first in the .img file:
<Char width="7" offset="0 10" rect="1 9 1 1" code=" "/>
the .img file is in hex:
07 01 01 00 0a ff ff
the format in fonts.h:
typedef struct
{
    uint8_t width;          // Width of glyph data in pixels
    uint8_t xrect;          // x width of rectangle
    uint8_t yrect;          // y height of rectangle
    int8_t xoffset;         // x offset of glyph in rectangle
    int8_t yoffset;         // y offset of glyph in rectangle
    const uint8_t *glyph;   // glyph pixel data
} glyph_t;

>> so we can see how the parsing is done.

In case of the "!":
<Char width="6" offset="2 3" rect="3 2 1 8" code="!"/>
.img:
06 01 08 02 03 00
>> the glyph data is indeed badly extracted in font.py

**Comment by CEngen1** [comment]
Good Job Mathieu !  Celebrate for a femtosecond, and then back to work!!

;)

**Comment by limpkin** [comment]
thanks again for your help :)
