### ISSUE TITLE
Can reboot Mooltipass with right touch input combination

### ISSUE THREAD

**Issue by 2CNK** [limpkin/mooltipass#150]
I can replicate this issue but sometimes need to try more than once to make it happen.

Setup to replicate the issue as I experienced it:

- MP has two credentials for a single website (in my case, webmail.showthegrow.com)
- Go to website to log in (e.g. http://webmail.showthegrow.com)
- MP prompts for one or the other credential to log in with
- Give MP a clockwise "dialing" input with finger as if using the jog-dial interface.  Uncertain whether it depends on duration of 'dial' or starting point.
- MP immediately scrolls up the bootup logo and remains that way.
- (If MP is unplugged here, the App becomes unresponsive.)  
- (If MP is left plugged in then the MP will eventually prompt for PIN and things will sort themselves out.)
- App icon is purple, log appended:
<pre>> requesting credentials for showthegrow.com
access denied or no credentials
device status: locked</pre>
- MP goes to "Enter your PIN" 
- App is responsive again, recognizes unlock of MP
- App Icon is cyan

Everything seems normal at this point. 

Windows 7 x64
MP App version 0.10.2
Extension version 0.2.0
Firmware: 0.7

**Comment by limpkin** [comment]
So what is happening is that i'm still taking into account the press of the credential choosing... so the MP will automatically launch the item on which your finger is (in that case the bottom right for the lock).
I'm thinking an unresponsive app is desired feature when MP is locked

Thanks for the awesome bug report btw.

**Comment by uniacke1** [comment]
I agree with Mathieu, this may be functioning as expected. 
After confirming credentials the MP will return to the home menu... and the next clockwise action from the right-hand dash button is the segment corresponding to 'Lock'.
Should be easy to confirm with some touch debugging output to see if this does indeed trigger the lock action from the homescreen.
Bjorn.

**Comment by limpkin** [comment]
already fixing it ;)

**Comment by 2CNK** [comment]
Ah, I see - the MP is queuing up the touch inputs and the particular way I end up doing it winds up triggering LOCK as a result (after processing the original input.)  Makes sense!
