### ISSUE TITLE
MP doesn't add new user/password when login with a new username and the logged page has a password field.

### ISSUE THREAD

**Issue by karman-san** [limpkin/mooltipass#153]
When login with a new user/password and the web that loads has a password field, MP tries to login again and waits for user input or timeout. In this moment if the user clicks 'yes' in the MP chrome app the MP ignores the request to add the new user/password.

This can be tested at http://karman.ath.cx/web/users/index.php with multiple users: admin/m00lt1p4ss, user2/pass2, user5/pass5.

**Comment by kasbah** [comment]
I think the issue is more that you shouldn't have a need to reset the app.
