### ISSUE TITLE
Allow longer passwords and/or alert user about truncation

### ISSUE THREAD

**Issue by myersjustinc** [limpkin/mooltipass#157]
Got my Mooltipass over the weekend and started trying to use it today. I tried using the Chrome app to load existing passwords onto it, but it appears to have truncated one of them to 31 characters:
![log entries including password truncation](https://cloud.githubusercontent.com/assets/764865/9043634/e190acae-39e4-11e5-8c90-8a2c030382fb.png)

I don't know which one it was because I was loading several passwords in a row and only noticed the truncation at all because I switched back to the logging tab at one point.

Two questions:

*   Can the Mooltipass store passwords longer than 31 characters? (Word-based generation systems such as [the xkcd method](http://preshing.com/20110811/xkcd-password-generator/) or [Diceware](http://world.std.com/~reinhold/diceware.html) can exceed this length rather easily.)
*   If not, can either the app or the device itself alert the user that their password is being truncated (i.e., corrupted!) and will not be the same as what originally was entered?

**Comment by limpkin** [comment]
Hello there,

- The password length is limited to 31 chars on the mooltipass.
- we'll add the domain name for the password trimmed message

**Comment by bwall** [comment]
If you don't mind me asking, what is the limiting factor keeping passwords at 31 characters?

**Comment by bryanlyon** [comment]
Our memory model requires a fixed length for all objects.  We also didn't
have a whole lot of space and had to use it the best ways we could.  We
decided that shortening the maximum password to allow for a larger number
of passwords.

**Comment by bwall** [comment]
Would it be feasible/reasonable to create a custom firmware image in order to increase the password size? I received my device today, and this limit was an unexpected surprise which greatly limits the viability of the device for my use cases.

**Comment by bryanlyon** [comment]
Of course, you're welcome to look at the code and modify it in any way you
wish.  It's all open source.  If you look back through the conversations
here you'll see the memory model and how it's changed.  You're also welcome
to ask for any help if you need it during your fork.

**Comment by uniacke1** [comment]
Depending on your needs, I think there's also something in the works for storing longer items - I can't find it offhand but I believe it was in relation to SSH keys.

**Comment by limpkin** [comment]
We are implementing it in our next generation device.
