### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by bortels** [limpkin/mooltipass#158]
Any documentation for the protocol, or import/export that the app does? Not that it's not fun to try to figure it all out looking at the source, but it's also nice to know for sure. (In particular - I want to write something to slurp up my keepass2 database and inject it into the mooltipass...)

**Comment by limpkin** [comment]
https://github.com/limpkin/mooltipass/tree/master/source_code/src/USB

https://github.com/limpkin/mooltipass/blob/master/tools/python_comms/mooltipass_coms.py#L787
