### ISSUE TITLE
inconvenient sorting in manual login

### ISSUE THREAD

**Issue by antonio-fr** [limpkin/mooltipass#160]
In manual login menu, domains are classified alphabetically, but from the first subdomain and not the main.
For example www.anywebsite.com, will be available in "w" and should be available in "a" because the main domain is "anywebsite".
If the sorting was from "main domain", this woul dbe much more convenient.

**Comment by limpkin** [comment]
Hello,

The app, extension are made in such a way that the www should never be stored in the device.
Could you let us know how you added them?

Regards

**Comment by antonio-fr** [comment]
Hi, I may added them manually. This may be the actual cause.

So you advise to enter as "domain.TLD" ?
 
Still, for Gmail, it was auaotmatically setup as "accounts.google.com", and should be classified as "g", not "a".

**Comment by limpkin** [comment]
The Mooltipass is made in such a way that domains and services should always be stored that way.
The particular point you bring up is tricky, as in your particular case you should store google.com.
Let's imagine the case where  you have website1.google.com and website2.google.com. In that case, users would prefer starting their search at 'w'.
