### ISSUE TITLE
where's the Chrome app's source code?

### ISSUE THREAD

**Issue by sardaukar** [limpkin/mooltipass#161]
I search the repo's code for "Allow Mooltipass" so I can see what the string being cut off is

![](http://i.imgur.com/0pceAVY.png)

but couldn't find it :/

**Comment by limpkin** [comment]
Hello Bruno,

https://github.com/sgillis/mooltipass.hid-app
You may click on the bottom right corner to increase the app's size ;)

Mathieu

**Comment by sardaukar** [comment]
Ah, didn't notice that :D sorry!
