### ISSUE TITLE
Password generator icon unavailable

### ISSUE THREAD

**Issue by 0xA000** [limpkin/mooltipass#166]
The MP extension settings, under password generator, mention that "An icon will be added to all password fields providing you a random password", yet it seems this does not always happen.

For example, when trying to sign up for a GitHub account, no icon was shown. Pointing out the password field manually by selecting custom credential fields did not help.

Also, suppose it did work, what would happen if you have to re-enter the same (generated) password and copy/paste is disabled (not uncommon on sign-up pages)?

I'm not sure if it is easy to implement, but would it not be easier if the MP itself could generate a random password and send it over USB/HID? On a typical sign-up page, a user would then enter a user name for the new account, navigate to the password field and ask the MP to generate and send a random password, navigate to the password verification field and ask the MP to re-send the same password. 

(After completing the sign-up, the extension would probably trigger the MP to ask to store the credentials as usual?)

**Comment by limpkin** [comment]
Hello there,

Github works perfectly fine for us... it is actually used for our presentation video in the setup page.
The issue you mention about password entering / password changing is in our todo list as well.

Regards

**Comment by 0xA000** [comment]
Hi,

Thanks for the quick reply. The issue was about signing up, not signing in. In the video, the user already has a GitHub account.

Regarding the scenario shown in the video, it almost works fine for me... There is only a minor thing where if you navigate to www.github.com, the front page defaults to "Sign Up" instead of "Sign In", and the MP already wants to enter my credentials in the sign-up fields. If I confirm on the MP, GitHub takes me to the sign-up page with my credentials pre-filled and an error saying this account already exists.

However, if I just ignore the message on the MP and click the "Sign In" button at the top, it works.

Cheers.

**Comment by limpkin** [comment]
year old issue, newer app and extension support cancelling requests.
