### ISSUE TITLE
Properly separate web sites

### ISSUE THREAD

**Issue by henryk** [limpkin/mooltipass#168]
Currently the context to look up an account seems to be solely defined by the last two components of the domain name. This is woefully insufficient, just thinking of *.co.uk…

In general terms, a web site is identified by a) protocol, b) fully qualified domain name, c) port number, d) base path. Each of these may represent a security boundary. See for example how cookies are handled in the browser (e.g. protocol distinction is opt-in, sub-domain and path matching may be enabled on a case-by-case basis).

Concretely: after storing an account for example.com/foo I was prompted to let the mooltipass use this account for blog.example.com, though at least I could add a second account for this site, and prevented from entering an account for example.com/bar.

It's O.K. to have a sort-of permissive default setting, but there should be an option to specify the context that a specific account is valid for with a regular expression. (Or, if you don't think your users can't handle that, a guided kind-of-regex-builder that is based on the four criteria above and lets the user enable or disable protocol and port match and set the match length for domain and path components, with a visual highlighting based on the current URL.)

**Comment by limpkin** [comment]
Hey henryk,

We're also here in the kind of scenario that could quickly get tricky.
Imagine a website X on which you could login via website.com/login and login.website.com
Please however note that in your scenario, our extension will allow you to store credentials for the blog.example.com website. Once you go back to this website, the mooltipass will first offer you the credentials for blog.example.com and then example.com.

The perfect solution in your scenario is to let the user select his rules. 
Would you be interested in contributing?

**Comment by htho** [comment]
Btw. are server certificates checked (Protection from phishing/DNS manipulation)?

**Comment by limpkin** [comment]
The URL showed on the mooltipass is the one extracted from your address bar.

**Comment by htho** [comment]
My question aimed at protection against phishing.
I suggest that the mooltipass plugin does not ask for the users credentials on a website without a server certificate that used have a certificate before. This way the user is (to a certain level) protected from phishing attacks where an attacker tries to impersonate the legitimate verifier.

**Comment by jnwatts** [comment]
Are you thinking similar to how SSH records the signature of remote hosts,
and reports if it changes?

**Comment by htho** [comment]
Well, the problem with that is, that certificates expire. Therefore the signatures change. Also certificates may become invalidated by the issuer if the private key got compromised.
I bet chrome warns if someone tries to mess with the certificates. I don't think chrome warns if a user tries to login to a website that was protected before, but now isn't.

That is the scenario I refer to: An attacker manipulates hostfiles, DNS-Servers or redirects traffic, to send users to a website that looks exactly like the one they want to login to. While the original website uses http*s*, that phishing site can only provide an http site, as faking a certificate is too hard. If I were a phisher that wouldn't bother me, there are so many users not checking if they are on an http or https website.
This is where the Mooltipass Plugin should warn the user: "Hey man! You're on a website that was secure before, but now isn't! Probably someone is trying to steal your credentials. I won't enter them here!" ;-)

**Comment by opie4624** [comment]
You know, it might make better sense to use the spinner controls during the "Save this username?" display to adjust the hostname wildcard. Maybe display the non-included portions as a lighter color?

**Comment by limpkin** [comment]
current extension supports public suffix list and has improved domain recognition capabilities.
