### ISSUE TITLE
Wish:

### ISSUE THREAD

**Issue by co-devs** [limpkin/mooltipass#169]
Would it be possible to add the ability to view passwords directly on the mooltipass?Being in the military, i cannot plug USB devices into the computers, so at the moment i have to use the mooltipass to enter my credentials into a text editor on my phone in order to view my password and enter it into the governmebt computer. Being able to view credentials directly on the mooltipass screen once unlocked would eliminate a lot of unnecessary steps when direct use of a USB port is not available.

**Comment by limpkin** [comment]
Hello there,

It is already possible, when the mooltipass is connected to a USB battery
only.

Regards

**Comment by co-devs** [comment]
Ah I see, I'll have to try that out. I think the ability to do that without
having to use a USB battery, such as when plugged into a smart phone or
even when plugged into a computer would be a useful feature. Thanks for the
quick reply!
Also, have there been any firmware updates for the mooltipass yet? I can't
seem to find anything regarding that

**Comment by limpkin** [comment]
Hello,

There is no current update for the mooltipass.

Regards

**Comment by htho** [comment]
"It is already possible, when the mooltipass is connected to a USB battery"

It is? I tried two powerbanks and was not able to.

**Comment by 2CNK** [comment]
I just confirmed it with a power bank and a power-only USB cable that 
has no data wires.  Unlock the device, then go to LOG IN menu.

"Enter username?" and "Enter password?" are replaced with "SHOW 
username?" and "SHOW password?" but otherwise function the same.

I'll be honest, I didn't know it could do this.  I like this feature.

**Comment by limpkin** [comment]
Hauke: you need to enable the feature in the settings tab of the mooltipass.

**Comment by uniacke1** [comment]
You should be able to "cheat" that by using a charge-only usb cable to power the device from any USB port :)

**Comment by htho** [comment]
In my case making the setting made it work without a power-only cable. (Who would be willing to carry that in *addidtion* to the normal cable anyway?)

Well the configuration tool is another story.
This is the default size of the Window:
![Screenshot of the Mooltpass configuration window](https://cloud.githubusercontent.com/assets/2182288/9959123/3478799c-5e11-11e5-84f4-79c220f413ab.png)

**Comment by limpkin** [comment]
Hauke,

As you are well aware we are currently redesigning our app.

**Comment by htho** [comment]
Limpkin,

I know you guys are improving the app. I wasn't aware it was a complete redesign. I am looking forward to the next version.

Regards.
