### ISSUE TITLE
Special character ignored without warning

### ISSUE THREAD

**Issue by jjkola** [limpkin/mooltipass#170]
I tried adding a password with symbol ¤ (U+00A4) from my Finnish keyboard and the saving succeeded but when I tried using the saved password I found out that the aforementioned symbol was missing from password. I tried saving the password both with chrome plugin as well as the hid app (by manually entering the password) and both behaved the same way with no indication of saving failure.

**Comment by limpkin** [comment]
Hello there,

Do you have this bug when using manual password recall?
If so it is normal as we currently only support ASCII characters.

Regards,
Mathieu

**Comment by jjkola** [comment]
Yes, it happens also when manually recalling the password. That was actually the way I verified the problem by directing the output to a notepad instead of user/password fields. In nordic code page (cp865) it is part of the extended ascii (code point 175). But if you support only standard ascii then it would be nice if there was notification to user that the password could not be saved as is instead of silently failing.

**Comment by limpkin** [comment]
Hello there,

Actually your password should normally be output when using the extension
in chrome. We will investigate that.

Regards

**Comment by jjkola** [comment]
If it is any help here is values for localization environment variables.
$ export | grep LANG
declare -x GDM_LANG="en_US"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US"
$ export | grep LC
declare -x LC_ADDRESS="fi_FI.UTF-8"
declare -x LC_IDENTIFICATION="fi_FI.UTF-8"
declare -x LC_MEASUREMENT="fi_FI.UTF-8"
declare -x LC_MONETARY="fi_FI.UTF-8"
declare -x LC_NAME="fi_FI.UTF-8"
declare -x LC_NUMERIC="fi_FI.UTF-8"
declare -x LC_PAPER="fi_FI.UTF-8"
declare -x LC_TELEPHONE="fi_FI.UTF-8"
declare -x LC_TIME="fi_FI.UTF-8"

And I'm using Chromium Version 44.0.2403.89 Ubuntu 14.04 (64-bit).

**Comment by limpkin** [comment]
Hey there,

Doing a follow up: are we still silently discarding non ascii chars in the app?

**Comment by bpascard** [comment]
@limpkin To answer your question : yes the app still silently discards non-ascii characters for both usernames and passwords.
