### ISSUE TITLE
Generate passwords on the device display

### ISSUE THREAD

**Issue by opie4624** [limpkin/mooltipass#171]
I'd love the ability to generate passwords on the device itself. Bonus points if it can save them with a short identifier in a context like "Offline PW Gen" or something similar.

**Comment by NicoHood** [comment]
I do not think this is required most time, but could be a handy feature if you are somewhere else and need to gen a new password without the host app. The password should be totally random though, but requires options like "a-z" "A-Z" "0-9" "Special chars".

I can imagine a menu with those 4 options where you can enable/disable them and then click right to generate a password. The length should also be considered.

Additionally it would make sense to ask the user "do you want to display the credentials?" if he does not want to input the user, nor the password.

**Comment by opie4624** [comment]
The way I imagined it, you would choose the options like you mentioned, then on the screen which showed your generated password, you could spin the dial to adjust the length, or keep tapping the Right button to generate another random password.

**Comment by pcapillon** [comment]
Hello,

I have implemented your feature for my own needs on the Mooltipass Mini. You can have a look at PR #216 which is currently being tested.
Due to code size constraints, it currently requires to disable some firmware features.

Cheers!
