### ISSUE TITLE
Room for additional options in Settings

### ISSUE THREAD

**Issue by opie4624** [limpkin/mooltipass#173]
I'd like to see the "Home" option removed from the circle and moved the the left arrow. This would make room for additional options in Settings (maybe rename it to Utilities?) for example: #171 or #172

**Comment by NicoHood** [comment]
I also think this is a good idea. On top of that I suggest to add a "right" key as in the favorites. This way you could change the keyboard layout on the device, which is extremely important for me. More offline options appreciated.

**Comment by NicoHood** [comment]
Another idea: a version identifier in the setting. aka "about" with also some credits, maybe something that scrols down or so.

**Comment by limpkin** [comment]
Main firmware development is happening on the mini now.

**Comment by 15495-4** [comment]
#555
