### ISSUE TITLE
Cannot access password

### ISSUE THREAD

**Issue by alesstimec** [limpkin/mooltipass#174]
Tried logging in with my credentials for github, the username is entered, the password is not..

Tried using the app to get the password, but the app say something like "Cannot access password" even though i enter the correct pin on the device..

**Comment by limpkin** [comment]
Hello there,

Please delete the credential inside the app and add a new one.

Regards

**Comment by alesstimec** [comment]
I am sorry, but being a programmer myself, this is NOT an answer i was expecting.. I bought the device to STORE my credentials SAFELY.. it does not seem to be doing the job, though.. 

Could you please at least give me the reason why this is happening?

**Comment by limpkin** [comment]
Hello,

We're currently working on changing that particular message actually. Another solution would be to simply enter your password on github so it is updated in the mooltipass memory.

Regards

**Comment by alesstimec** [comment]
The problem is that i loose access to passwords when i add the to Favourites.. hmm..

**Comment by limpkin** [comment]
Are you sure? 

We tried replicating this problem, without success.

**Comment by limpkin** [comment]
a temporary patch has just been pushed. You won't see this message in app 1.0.19

**Comment by alesstimec** [comment]
Hi, 

yes, quite sure.. i had to delete all credentials that were in my favourites.. i could access all others..

**Comment by limpkin** [comment]
In an hour or two you'll be able to manually force an extension update in chrome.
Could you try replicating this bug, and if so write us here a detailed step by step guide?

**Comment by alesstimec** [comment]
Will do.. thanks!

**Comment by limpkin** [comment]
Hello,

Could you confirm that it solved your bug?

Regards
