### ISSUE TITLE
"Don't show these messages" button non-functional

### ISSUE THREAD

**Issue by opie4624** [limpkin/mooltipass#176]

**Comment by limpkin** [comment]
Hello,

Can you provide more details? It has been tested over and over again.
However, the notifications will start appearing after a reboot.

**Comment by opie4624** [comment]
Clicking the "Don't show these messages" button does nothing at all. It doesn't dismiss the notification, or stop them from appearing. I can provide a debug log if you tell me how to produce one.

**Comment by limpkin** [comment]
Hello,

We just tried to reproduce this bug, without success. Could you make a quick little video and upload it somewhere?

Regards

**Comment by limpkin** [comment]
solved
