### ISSUE TITLE
Chrome App falsely claims device to be locked.

### ISSUE THREAD

**Issue by cornelinux** [limpkin/mooltipass#199]
When visiting a website the popup occurs which claims the device to be locked - although the device is not.

**Comment by limpkin** [comment]
Hello,

Can you open the app and make sure it also sees it unlocked?

Thanks

**Comment by cornelinux** [comment]
Hi Mathieu,

I am really sorry for bothering. When you asked I checked and I was running a terrible old version of extension and app. I was not aware I did not install from the app store.
After installing the latest version, everything works fine.
If I ever get the effect again - which I doubt a lot - I will reopen.

Thanks for the really quick reply.

Kind regards
Cornelius

**Comment by limpkin** [comment]
Great! :)
