### ISSUE TITLE
CMD_SET_BOOTLOADER_PWD and CMD_JUMP_TO_BOOTLOADER undocumented

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#202]
Those commands are missing in the USB docs:
https://github.com/limpkin/mooltipass/tree/master/source_code/src/USB

You can find the functionality here:
https://github.com/limpkin/mooltipass/blob/f5dfb480ba2d19d0a257ff107b612ff306fc2905/source_code/src/USB/usb_cmd_parser.c

And an example here:
https://github.com/limpkin/mooltipass/blob/master/tools/unlockUpdateLock/unlockUpdateLock.py

**Comment by limpkin** [comment]
if you have so much spare time to find undocumented commands I have some tasks for you if you're interested ;)
