### ISSUE TITLE
Card can not move between devices

### ISSUE THREAD

**Issue by myjanky** [limpkin/mooltipass#203]
So I encrypted a card on one mooltipass device, took it to another PC with an mooltipass and it says invalid card. 

Have not dived into the code yet but I am sure this can be achieved.

**Comment by limpkin** [comment]
Hello there,

Your other mooltipass doesn't know this card. If you start the app on the other mooltipass, it'll ask you for your database file.

**Comment by myjanky** [comment]
Thanks @limpkin 
Exactly what I was looking for.
