### ISSUE TITLE
Device feature request: Organize the device credential selector by domain

### ISSUE THREAD

**Issue by eddiezab** [limpkin/mooltipass#204]
Currently when credentials are on a device they are ordered by subdomain.domain.com. This becomes problematic when dealing with common subdomains. For example:

accounts.google.com
accounts.domain1.com
accounts.domain2.com.

This is also causes subdomains to potentially be listed in different locations when selection (accounts.google.com, b, c, d.... google.com).

My suggestion would be to group the credentials by the domain, keeping subdomains (if added) listed under that domain. For example:

domain1.com
 - accounts
 - www

google.com
 - accounts

**Comment by limpkin** [comment]
Hello there,

This is understandable, however it may be debated why one may store generic domain prefixes. When we first designed this system, we figured users would only store prefix.domain.com if the prefix was important (such as accounting.domain1.com & email.domain1.com)

**Comment by eddiezab** [comment]
For the cases where the app can do the logging in, it's not a big deal. This is meant to deal with manual entry.

Thank you for your explanation. I can see your reasoning, but I would like to attempt to clarify my position through another example. 

You need to log into a site that you haven't been to in some time. The full domain of the site that you're attempting to log into is account.foobar.com. Where will you find that credential? And now you're probably asking yourself is, "that depends, did you save account.foobar.com, or foobar.com", and it's that ambiguity that I'm trying to address. Now the issue gets further compounded if account.foobar.com is the 5th account.domain.com in the list.

I just thing that  domain -> prefix (if any) -> account is more intuitive and user-friendly than requiring the user to remember specifically, especially because the potential (and proven) name clashing in prefixes. 

Thanks for the great product.

**Comment by limpkin** [comment]
Hello,

Thanks for the compliment :)
You're right, but in that case you'd scroll through accounts.foobar.com before reaching foobar.com... but I agree that'd be another check from the user.
On the other side of the coin (something that I forgot to mention) is this particular scenario: domain1.generichostingcompany.com & domain2.generichostingcompany.com)... and I can understand that in that case users would prefer sorting using the prefix.
