### ISSUE TITLE
Mooltipass Mini Beta Bugs

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#207]
Here is a list of bugs that I found while using the MP Mini (will get updates over the time):

* [x] Open Management mode, add a new entry, save and then do not accept the password on the device. If you read the password afterwards it will have random chars.

* [x] The "T" in "Settings" has a very thin "|".

* [x] If you set the brightness in the app, but the device is locked and then unlock it, it will gives an "okay" but the brightness is not applied.

* [ ] Suggestion: If you hold the button, something visually should tell you that something happens and possibly how long you have to hold. This way you can get more feedback that this function is available.

**Comment by limpkin** [comment]
Open Management mode, add a new entry, save and then do not accept the password on the device. If you read the password afterwards it will have random chars.

>> what would you actually expect? we can't simply encrypt \x00.... as we'd encrypt a known plain text.

 The "T" in "Settings" has a very thin "|".
>> "bug". If it was 2 pixels wide it wouldn't be centered.

If you set the brightness in the app, but the device is locked and then unlock it, it will gives an "okay" but the brightness is not applied.
>> brightness is set dynamically

**Comment by limpkin** [comment]
About the suggestion: didn't you read the tutorial?

**Comment by NicoHood** [comment]
No, I asked if there is any additional docs. Where can I find a tutorial?

The brightness bug is not fixed. Just because you cannot reproduce it, doesnt mean it does not exist. I could reproduce it several times until it did not appear anymore. I guess that has something to do with the locking timeout.

**Comment by limpkin** [comment]
A tutorial should be displayed at the device boot. If it hasn't you can
enable it again the settings tab of the app.

**Comment by NicoHood** [comment]
It was not displayed. (new bug?)

**Comment by limpkin** [comment]
no, maybe because i haven't enabled it when i shipped your device

**Comment by NicoHood** [comment]
I suggest to do a last "press the wheel to continue" as the end, as i scrolled to fast for example and the tutorial disappeared. But I really like the tutorial!!!

**Comment by NicoHood** [comment]
How to reproduce:
Set brightness to 20%
Lock the device, go to the pin entering menu, set brightness to 100%, 20%, 100% and when unlocking it is still 20%.

**Comment by limpkin** [comment]
that's quite a way to reproduce it...

**Comment by limpkin** [comment]
please reopen the issue with the correct format so I can assign someone on it.
