### ISSUE TITLE
Cannot access some passwords with V1

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#217]
I am using the first Mooltipass Hardware (the large one) with Firmware V1. I do not know if this got fixed in the update, but I did not dare to update yet.

I've a lot of entries starting with the letter "k".
However if I search for "k" there are only 4 entries, I cannot click "right" to set the 2nd letter.
If I switch to "l" and then back to "k" I do get the "right" option and now can browse all "k" entries.
If I go further to "j" I can also browse "j" to the right. But "j" does not even has a single entry.
Going to "i" gives the expected behaviour again. I have 1 entry with "i".

**Comment by limpkin** [comment]
once again, please give us a clear how to guide to reproduce the bug.

**Comment by NicoHood** [comment]
I've written it above. Its as clear as possible.

**Comment by limpkin** [comment]
can you create a new user with an empty DB and add credentials until you can reproduce the bug?

**Comment by limpkin** [comment]
please reopen the issue following the dedicated template.
