### ISSUE TITLE
Merging credentials

### ISSUE THREAD

**Issue by 0xA000** [limpkin/mooltipass#220]
### Missing feature

A way to synchronize the set of credentials between two mooltipass devices. For example, by creating a variant of the "import from file" function that merges the imported set of credentials with the existing set of credentials (instead of overwriting the existing credentials). Alternatively, a way to merge two or more sets of exported credentials. The merged set could then be imported as usual.
### Justification

I'm using two mooltipass devices, one at home and one at work. New credentials get added to one or the other mooltipass, depending on where I happen to be, so over time they get out of sync. It would be very convenient to be able to merge the sets of credentials between the two devices.
### Workarounds

None.

**Comment by limpkin** [comment]
Hello there!

Actually the merge feature is already implemented in the backend code (just needs to be enabled), but we don't show it to the user to not confuse him. We figured the best way would therefore be to implement a merging interface like you suggested. Hopefully we'll have time and resources to implement it in the near future.

**Comment by NoahAndrews** [comment]
Is there a command line utility that lets you do the merge?

**Comment by limpkin** [comment]
A smart merge? Unfortunately not.

**Comment by NoahAndrews** [comment]
Unfortunate. Looking forward to the implementation of this into the app then!

**Comment by gvandewaetere** [comment]
+1 for merger or synchronisation feature! I also have one at home and one at work. I am actually never using the two mooltipasses at the same time. So auto backup and import to e.g. google drive would be cool! Maybe you could implement a popup, asking you to update your mooltipass if a newer backup copy is available.

**Comment by NicoHood** [comment]
@gvandewaetere I hope you are aware that only password fields are encrypted and the username, website and comment are not? I'd never upload anything to google drive or other cloud servives.

A merge mode that does not delete entries would be nice though.

**Comment by RChadwick7** [comment]
+1 for sync feature. Sync should be the default. With the current method of the file overwriting credentials, it is too easy to accidentally restore a small or old file, wiping out saved passwords. The only way passwords should be removed is if one manually deletes it. This would be a safety issue. Auto-backups would be fantastic. I also would not want to upload my password database, encrypted or not, to Google, the NSA, or anyone else.

**Comment by limpkin** [comment]
hey everyone,
I've recently added this feature to moolticute, to which we'll be migrating in the medium/long term.
With the upcoming death of chrome apps and the unnecessary processes that mooltiapp has, it makes sense to migrate to an application made from the ground up.
We'll make a call for beta testers in the coming month.
