### ISSUE TITLE
Feature Request: button press after demo

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#224]
### Missing feature
In the initital demo/instruction you need to scroll down you can use the scroll wheel to go through all pages. If you accidentially scroll down too much the demo is over and you missed how button presses work. It should require a button press in the demo to go forth and one at least to go back, so the user has at least tried all options once.

### Justification
I personally missed the demo two times. Not that I need it essentially, but normal users should see it right. Cause first you do not know how to get it back. And you might wonder if you missed something important.

### Workarounds
Reenable the demo in the settings via the APP.

**Comment by limpkin** [comment]
During the demo you can have a long press or a 'wheel up' to scroll back.
In the future, please mention this 'issue' is for the mini.

**Comment by NicoHood** [comment]
Yes you can do it. But it is not forced. I already described that and why it is important to force that the user tries this one time.

**Comment by NicoHood** [comment]
I just checked the latest demo, it does not work as expected. Please note that button press etc all works, but its not forced. Details above.
