### ISSUE TITLE
Mini User manual notes

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#225]
Those are just suggestions, my english in not perfect. Something might be personal preferences. Just writing down what I noticed. Hope it will help.

* I cannot mark/copy text from the manual
* Page 3: "Simply insert one of the cards you received ~~in~~ **into** the Mooltipass Mini."
* Page 3: "Click ~~on~~ the wheel.. ~~Scrolling to the cross icon and clicking~~ **Selecting the "X" icon** or ... ~~denies~~ **aborts**" 
* Page 4: ".. can be ~~one of the~~ digests 0-9 or ~~one of the~~ letters A-F."
* Page 4: "the main menu will be displayed ~~to you~~."
* Page 4: "Congratulations, your Mooltipass Mini and the smart card are set up **successfully** and ready to use!"
* Page 5: "Visit any website login and **enter your login + password**." (or as alternative ; < ,)
* Page 5: "... always ask you for **permission(s?)** to use or change information you have stored ~~in it~~."
* Page 5: "..will ask ~~your permission~~ **for your permission** to enter ~~your~~ credentials" (or as alternative remove "for your" instead of the "your".)
* Page 6: "click ~~on~~ the wheel."
* Page 7: "will then promt you to ~~accept~~ **type**" (for login and password)
* Page 8: "You may use the 'credentials' tab of our app.." Wait what? Adding credentials via extension was explained, but not via APP. It should be explained before, so this section is missing. Especially if you are not using chrome or just want to add non website credentials for offline passwords. I suggest adding this section after II and then refer to it in II as alternative methode for offline passwords/without chrome to skip to this next section. And then in IV the reference is valid.
* Page 14: "~~Otherwise accept it~~"
* Page 15: "~~Clicking on it will bring its menu.~~ **Clicking the icon shows its menu.**"
* Page 16: Green? The picture has a blue icon?
* Page 16: I do not understand the 2nd paragraph. Why would one use a password gen in a login field? What is a credential submit event? What does credential storage procedure mean?
* Page 16: last sentence the dot (.) is missing.
* Page 17: "Among ~~others~~ **other settings**, the ~~settings~~ ..."
* Page 17: Blacklisted websites? What is this?
* Page 18: "please make sure to correctly ~~select~~ **set** your ..."
* Page 19: The picture is outdated
* Page 19: "you can get access to ~~our~~ **the** credential management interface."
* Page 19: It should be highlighted that the description field and also the user/site field is NOT encrypted, only the password. Because in the section before you also described that you can store the data int he cloud. And I personally would place security questions as additional description to an entry. But this would be highly critical if the database export is stored in the cloud. Its like uploading a clear password text file.
* Page 20: I do not understand the synchronizing. The app needs to be open before? Why a backup of the data, isnt it more a restore? Thats unclear to me.
* Page 20: Best security Practices: [Regulary changing the card pin and services passwords](https://www.google.de/search?q=changing+passwords+often+not+good&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=7x6wV_O0Gove8ger9IDQDg) ([This one](https://www.wired.com/2016/03/want-safer-passwords-dont-change-often/) is good) Especially the service/website passwords should not be changed, if you use the random password generator, because they are highly safe then. If someone hacks them there is another more critical bug in the system.
* Page 20: The support address can be written in clear text, as it is a PDF. And if you get spam, that's it for this address then.

**Comment by limpkin** [comment]
it is noted.
