### ISSUE TITLE
[Chrome App] jquery.min.js not found

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#244]
### Expected behavior
The app lanches without errors.

### Actual behavior
The app launches but hangs in the loading screen.
```
chrome-extension://mgjklikjjnnnpkmocccndgeicngjiaap/html/bower_components/jquery/dist/jquery.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
datatables.min.js:175 Uncaught ReferenceError: jQuery is not defined
jquery.tooltipster.min.js:1 Uncaught ReferenceError: jQuery is not defined
app.js:238 Uncaught ReferenceError: $ is not defined
device.js:7 Uncaught SyntaxError: Unexpected token <<
credentials.js:9 Uncaught ReferenceError: $ is not defined
shortcuts.js:16 Uncaught ReferenceError: $ is not defined
```

### Step by step guide to reproduce the problem
Install chromium on Archlinux and the app via local folder. Other linux distributions might also be affected.

This commit seem to break the App, as this file gets deleted there:
https://github.com/limpkin/mooltipass/commit/530b6cccc0b6b70eaec5265fc3117f82fbaf5938

**Comment by limpkin** [comment]
did you install from the repo? 
If so, it seems we encountered a bug in github when moving folders around.

**Comment by NicoHood** [comment]
Problem solved now. Many thanks :)
