### ISSUE TITLE
[Mini Firmware] Card Unlocked notice inconsistent

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#262]
### Expected behavior
If you insert a card and unlock it you get a message "Card unlocked". If you manually lock the device and then unlock it again it does not say that message.

### Actual behavior
The message should be shown.

### Step by step guide to reproduce the problem
Described above

### Mooltipass version
v0.7 (current master) but self compiled for MP Mini

**Comment by limpkin** [comment]
"fixed" in https://github.com/limpkin/mooltipass/commit/fc7c0bee5253ec51e34bd6a460b9bc81666100fa
