### ISSUE TITLE
[Mini Firmware] Credentials are ordered wrong

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#263]
### Expected behavior
If you insert a new Credential its ordered in an alphabetic order, starting with "a-z" (and somewhere the special characters)

### Actual behavior
Under some special circumstances it seem that the ordering failes and the credentials are ordered wrong.

### Step by step guide to reproduce the problem
* Create a new user.
* Use the MP App with the quick add menu to add new entries (no username, random password)
```
äöütest
öäütest
abc""""
ae2
ae3
ae1"""""""
gjtyjytj
zzzzzzzzzzzzzzzzzzzzz
!"#$%& '()*+,-./:;<=>?@[\]^_`{|}~
aaaa
```

Now some of them might not be required to trigger the bug. Thats at least one 100% reproduceable order. I will try to shrink that and edit my post below. Its possibly caused by the utf8 chars. You will notice that the new "aaaa" entry is at a completely different place than the other entries starting with "a". And you will also notice that on the left side, if you scroll to "zzz.." the next entry is "-" but it should be "ä". This bug continues on the left side if you scroll around a bit (edit: this seems to be an independant different bug: https://github.com/limpkin/mooltipass/issues/266). The login order is totally messed up now.

Smaller testcase:
```
äöütest
abcdef
zzzzzzzzzzzzzzzzzzzzz
!"#$%& '()*+,-./:;<=>?@[\]^_`{|}~
aaaa
```

The integrity check seems to fix that ordering. However if the node management on the device goes wrong there is possibly that this bugs triggers other data loss or overwriting of other user nodes.

### Mooltipass version
v0.7 (current master) but self compiled for MP Mini

**Comment by limpkin** [comment]
Once again, Mooltipass doesn't support non ASCII chars.
You can't therefore ordering to work when you deliberately introduce UTF8 chars.

**Comment by NicoHood** [comment]
If Mooltipass does not support UTF8 at all, then it should check if the input characters are valid ASCII chars <128, so that such errors can never happen. Also its confusing to me that ae works but oe not.

On top of that the App should also warn you about this when entering the data, but the firmware should also check it to avoid memory bugs like this.

**Comment by limpkin** [comment]
which is why i left https://github.com/limpkin/mooltipass/issues/260 opened.

**Comment by NicoHood** [comment]
valid
