### ISSUE TITLE
[Mini Firmware] Use App to exit blocks USB

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#264]
### Expected behavior
If you perform an integrity check and flip the wheel it should give a warning but not block the App from transmitting usb data.

### Actual behavior
The message block the usb transfer for the time of showing the message.

### Step by step guide to reproduce the problem
Perform an integrity check and flip the wheel. The integrity check will stop for a while. It will not fail, but stop. This could be intendet, but as the usb stuff is interrupt driven I think this can be gui independant possibly.

### Mooltipass version
v0.7 (current master) but self compiled for MP Mini

**Comment by limpkin** [comment]
**temporarily** blocks USB.

We don't have multi-threading in the microcontroller so this isn't going to change.

**Comment by NicoHood** [comment]
I thought it could possibly solved in the background timers.

However I've tested if you can ever get the APP to timeout and this does not seem to be the fact. So that bug is just cosmetic and not a problem.
