### ISSUE TITLE
[Mini Firmware] Card removal on User creation destroys it irreversible

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#267]
### Actual behavior
If you add a new user and then remove the card while "processing" it gives no error and finishs without problems. However if you reinsert the card the pin is wrong (I used 0000). Trying the pin 3 times breaks the card.

### Expected behavior
Even if the card breakage is expected there should be a critical error message and the user should be deleted afterwards. If not the user is left in the memory forever. Second it might be possible to setup the card first, so there is very little time for the user to remove it while it gets inititalized. Then the user should be created.

For me as User I am wondering if I can reset the card or if its forever broken now. (I really do not know, can I trash the card?)

### Step by step guide to reproduce the problem
Add a new user and remove the card while "processing...".

Edit:
My 2nd mooltipass asks me to add a new user, so the smartcard is possibly not broken. However there should be a way to enable it on the initital MP again.

### Mooltipass version
v0.7 (current master) but self compiled for MP Mini

**Comment by limpkin** [comment]
Do you realize that by doing that you're actively trying to corrupt the data being written in the card?
Do you unplug your computer cord when it is processing data?
How is this an issue when it is common sense that one shouldn't do that?

**Comment by NicoHood** [comment]
This might happen if the card is not fully inserted. I also sometimes had those problems, thatswhy I tested this. That this is not a good idea we all know. I just wanted to let you know that such situations cause serious trouble.

**Comment by limpkin** [comment]
"This might happen if the card is not fully inserted.": no it won't, we designed our device to actually prevent that.
