### ISSUE TITLE
Pipe symbol wrong?

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#280]
The pipe symbol `|` int he Mini font has a cut in the middle. But only for the small font, not that 2 larger fonts used on the left side when scrolling credentials (at least with my fix).

I am not sure if this is on purpose, but it seems wrong to me. I can correct this if you wish.
# Steps to reproduce:

Add a credential with the name "|pipe|" to you mooltipass and check the font on the device itself. You will see a pixel in the middle is blank.

**Comment by limpkin** [comment]
it's the font itself.

**Comment by NicoHood** [comment]
I know. My question was if we should fix the font. From my point of view it would make sense. I can do that if you wish.

**Comment by limpkin** [comment]
I think it is fine.

**Comment by NicoHood** [comment]
I think you should ask other people as well on that.
