### ISSUE TITLE
Windows 7 Lockscreen Mooltipass Prompt

### ISSUE THREAD

**Issue by sonofapharmacist** [limpkin/mooltipass#287]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
On Windows 7 locked desktop, mooltipass input/output should not subvert lock screen and should only be able to communicate with lock screen password field.  
### Actual behavior
In Windows 7 on locked desktop a website's login timed out and went back to login (assuming, since this is regular behavior i have with this website) as I was prompted on my unlocked mooltipass to enter credentials for the website. I don't know that my credentials submitted.
### Step by step guide to reproduce the problem
Login to site you are normally prompted for on mooltipass, which also times out login.  Lock desktop, wait for timeout for prompt assuming your mooltipass timeout is longer.
### Mooltipass version
Which Mooltipass do you use? Big black one. What is its firmware version? v1  

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello,

Thanks for the bug report. However, why would this behavior be a problem when a user could get logged in on his own session and not someone else's?
