### ISSUE TITLE
cppcheck reports various warnings

### ISSUE THREAD

**Issue by jburgess777** [limpkin/mooltipass#297]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
No warnings when running cppcheck

### Actual behavior
$ cppcheck . > /dev/null                                                                                                                                                                     
[arduino/standard/libraries/oledmp/oledmp.cpp:191]: (error) va_list 'ap' was opened but not closed by va_end().                                                                              
[arduino/standard/libraries/oledmp/oledmp.cpp:202]: (error) va_list 'ap' was opened but not closed by va_end().                                                                              
[bootloader/standard/LUFA-111009/Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c:804]: (error) Resource leak: fp                                                                          
[bootloader/standard/LUFA-111009/Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c:934]: (error) va_list 'ap' was opened but not closed by va_end().                                        
[bootloader/standard/LUFA-111009/Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c:956]: (error) va_list 'ap' was opened but not closed by va_end().                                        
[source_code/src/OLEDMP/oledmp.c:1115]: (error) va_list 'ap' was opened but not closed by va_end().                                                                                          
[source_code/src/OLEDMP/oledmp.c:1134]: (error) va_list 'ap' was opened but not closed by va_end().                                                                                          
[source_code/src/USB/usb.c:939]: (error) va_list 'ap' was opened but not closed by va_end().                                                                                                 
[source_code/src/USB/usb.c:964]: (error) va_list 'ap' was opened but not closed by va_end().                                                                                                 

### Step by step guide to reproduce the problem
git clone https://github.com/limpkin/mooltipass.git
cd mooltipass
cppcheck . > /dev/null

### Mooltipass version
I do not have any mooltipass hardware

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
a quick word to say that I haven't forgotten about this bug, but that in anyway this code isn't used.

**Comment by limpkin** [comment]
discard latest commit.... wrong referencing number.
