### ISSUE TITLE
checkTextField() limits valid string size to 61 characters and could read bytes beyond data buffer

### ISSUE THREAD

**Issue by jburgess777** [limpkin/mooltipass#298]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Avoid assuming that strings being checked in checkTextField() are terminated by 0 since this data comes from an untrusted 3rd party. Code should not read beyond end of incomingData buffer to avoid undefined behaviour. It looks like the maximum login length supported by CMD_SET_LOGIN was expected to be 62 characters.
### Actual behavior
The code in checkTextField() attempts to validate the length and string length fields with:

    // Check that the advertised length is correct, that it is not null and isn't bigger than a data packet
    if ((len > max_len) || (len == 0) || (len != strlen((char*)data)+1) || (len > (RAWHID_RX_SIZE-HID_DATA_START)))

The current mooltipass_hid_device.py appears to always put a 0 on the end of the string and includes this in the "len" value. Since the HID packet is limited to 64 bytes adding this 0 reduces the maximum available string size by 1 byte. The maximum string length that the device will process is 61 characters, with a HID packet of 64 bytes: len(1) + cmd(1) + ascii(61) + nul(1). 

In a CMD_SET_LOGIN request the device attempts to support a 62 character login name + nul (NODE_CHILD_SIZE_OF_LOGIN == 63) but it is only possible to use 61 characters due to the limitation above.

If another program sent commands to the device then it might not include the terminating 0. This would cause the strlen() to read undefined data within or possibly beyond the end of incomingData and return an incorrect length. One option would be to extend the data buffer by one byte and set this to 0. This would prevent the strlen reading beyond the end of the array even if the HID message did not contain any nul character.

### Step by step guide to reproduce the problem
This is from a code review and has not been reproduced in practice.
### Mooltipass version
I don't currently have a mooltipass device, I'm waiting to receive one from the kickstarter campaign.
8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello,

Your text is correct. **However**, having strlen read data after the end of the buffer isn't a problem in itself. In any case, we'll change the strlen call to a strnlen

**Comment by jburgess777** [comment]
I agree it will likely read a few bytes of random data off the stack, find a 0 and return an incorrect length which will cause the command to be rejected.

**Comment by limpkin** [comment]
Hello,

https://github.com/limpkin/mooltipass/commit/54d3860225608ba62452ff06794a2e1cd82f224a was pushed.

Can you double check that it is alright with you as well?

**Comment by limpkin** [comment]
Hello?
