### ISSUE TITLE
Add MP Mini enclosure drawings

### ISSUE THREAD

**Issue by kbembedded** [limpkin/mooltipass#314]
### Missing feature
MP Mini case CAD files not present.

### Justification
Want to make custom enclosure with modifications.

### Workarounds
N/A

**Comment by limpkin** [comment]
Will add it when I'm back from fosdem!

**Comment by kbembedded** [comment]
Would it be possible to add the original source files rather than just the .STL?  Trying to get an enclosure made in something that the controller software doesn't like the STL files themselves.  Would be easier to redraw from blueprints rather than keep whacking away at the current pace.
