### ISSUE TITLE
Issues with chrome+mooltipass extension+roll20.net

### ISSUE THREAD

**Issue by ReonBalisty** [limpkin/mooltipass#345]
<------------------------ BUG REPORT -----------------------------------------
### Actual behavior
[Issue](https://app.roll20.net/forum/post/4792870/issue-with-forms-slash-charactersheet-titles-and-buttons-buttons-over-text-chrome/?pageforid=4792870#post-4792870)

### Step by step guide to reproduce the problem
Turn on the mooltipass extension to recreate the problem, it is easily fixed by turning off the mooltipass extension. It is the only extension that creates the issue shown in the above url within the image submitted to their admins/mods/devs

### Mooltipass version
Which Mooltipass do you use?
original Firmwar v1 (also have inquiry into how to update my firmware, which has not been answered on the process)

**Comment by limpkin** [comment]
thanks for the report!

@Gastonius can you look into that please?

**Comment by Gastonius** [comment]
Sure, created an account and tried to get to the same spot without luck.

I reached into the editor, and I was able to see other popups (which worked fine), I just was unable to reach into the same popup as shown in the picture, which seems to have a problem.

I also found out that chrome extension was unable to store credentials for roll20.net, so: added it to my list.

**Comment by ReonBalisty** [comment]
Within the App.roll20.net>Join game>Journal tab>[create a handout] then open the handout>title area shows the same on any laptop and desktop I try it on within Chrome.

**Comment by Gastonius** [comment]
Great, thank you very much! I was able to identify the issue and fix it, it will be available in the next release

**Comment by limpkin** [comment]
Hello @ReonBalisty I have just pushed an update to the extension. Could you uninstall yours and add the one our testers use? https://chrome.google.com/webstore/detail/mkjlelalgdinanmcljpgkojjolkdcebh

**Comment by ReonBalisty** [comment]
Should probably be re-opened, as this still is interfering with the closing of the pop-out overlay. There is not an "X" in the upper right hand corner of the forms whilst the Mooltipass Extension is open, tested it this weekend and had to disable the extension while in the midst of playing a game so that I could close the overlaying windows properly. 
I have installed the tester extension for now.

**Comment by limpkin** [comment]
@Gastonius seems you have some work! :)

**Comment by limpkin** [comment]
Hello there,

we have just pushed an update to our extension. Could you confirm you still have the issue?

Regards

**Comment by ReonBalisty** [comment]
While Extension is on:
![issue04012017](https://cloud.githubusercontent.com/assets/8903224/24580776/209f70f8-16c3-11e7-9937-499cf5028380.jpg)
While it is off:
![issue04012017-2](https://cloud.githubusercontent.com/assets/8903224/24580782/356acb22-16c3-11e7-8cf0-4db9f4271be0.jpg)

**Comment by Gastonius** [comment]
Hello ReonBalisty, 

The last update (to be released in a few hours) contains a fix to prevent that. While I couldn't find a popup with the x as shown in your screenshot, we aren't using jquery-ui css now, so I trust that once you get the updated version of MooltiPass extension it will be working fine. Here's an screenshot:

<img width="963" alt="screen shot 2017-04-05 at 12 02 06 am" src="https://cloud.githubusercontent.com/assets/3153540/24687988/746c49f4-1993-11e7-8e8b-4a1d955ba29b.png">

**Comment by ReonBalisty** [comment]
While off and inspected:
![image](https://cloud.githubusercontent.com/assets/8903224/24688462/f2d11924-1974-11e7-8b1f-cda1d941746a.png)

**Comment by limpkin** [comment]
👍

**Comment by limpkin** [comment]
.73 pushed! please confirm if it solves your problem.

**Comment by ReonBalisty** [comment]
The problem of the missing "x" is still persistent within the new .73 build. If I can present more information to help out, please say so.

**Comment by limpkin** [comment]
hey there!
we've just pushed .74... could you let us know if that did it?

**Comment by ReonBalisty** [comment]
.74 is a solution that shows the "x" that was missing and it is functional.
