### ISSUE TITLE
Unable to build MP mini bootloader, too large

### ISSUE THREAD

**Issue by kbembedded** [limpkin/mooltipass#348]
### Expected behavior
Building bootloader will succeed and be the correct size.

### Actual behavior
If building bootloader from source_code/ directory with BOOTLOADER = true, the resulting output is too large.  Running it through the python function generateFlashAndEepromHex() returns: 
Firmware file is 28538 bytes long
Extracted firmware version: v1.2
Bootloader file too long: 4316 bytes long

If building bootloader from source_code/src/ directory with BOOTLOADER = true, the build fails with the following:
avr-gcc obj/flash_test.o obj/flash_mem.o obj/spi.o obj/aes256_ctr.o obj/aes256_nessie_test.o obj/aes256_ctr_test.o obj/aes.o obj/bootloader_main.o -o mooltipass_bootloader.elf -lm -Wl,-Map=mooltipass_bootloader.map,--cref -Wl,--gc-sections -Wl,--relax -mmcu=atmega32u4 -Werror -Wl,--section-start=.text=0x7000 -Wl,--section-start=.spmfunc=0x7F80 -Wl,--undefined=spmfunc
/usr/lib/gcc/avr/4.9.2/../../../avr/bin/ld: section .spmfunc loaded at [0000000000007f80,0000000000007fff] overlaps section .text loaded at [0000000000007000,000000000000804f]

Unless I am missing something in documentation, I believe I am correctly attempting to build for the MP mini and am attempting to do so correctly.

I will continue to investigate this, but after a couple of hours I am still no closer to understanding what is going on.

### Step by step guide to reproduce the problem
This was achieved with avr-gcc version 4.9.2 on 64bit Ubuntu Xenial 16.04 installed from apt.
Navigate to source_code/ or souce_code/src/ as noted above and attempt to run 'make' with the BOOTLOADER = true option set in the makefile.

### Mooltipass version
Not really applicable.  I have a couple of mini's I've built from scratch that I am intending to do some testing on.  Am attempting to run through the bootstrapping process you have.  Documentation is pretty limited, but I believe I am on the right track.

**Comment by limpkin** [comment]
Hello there,

It has been quite a while since someone tried to build the bootloader from
the Linux makefile, we apologize for that.
Could you first make sure that the makefile adds a  MINI_BOOTLOADER define
when compiling?

That might be what you are missing.



On Mar 22, 2017 6:51 AM, "kbembedded" <notifications@github.com> wrote:

Expected behavior

Building bootloader will succeed and be the correct size.
Actual behavior

If building bootloader from source_code/ directory with BOOTLOADER = true,
the resulting output is too large. Running it through the python function
generateFlashAndEepromHex() returns:
Firmware file is 28538 bytes long
Extracted firmware version: v1.2
Bootloader file too long: 4316 bytes long

If building bootloader from source_code/src/ directory with BOOTLOADER =
true, the build fails with the following:
avr-gcc obj/flash_test.o obj/flash_mem.o obj/spi.o obj/aes256_ctr.o
obj/aes256_nessie_test.o obj/aes256_ctr_test.o obj/aes.o
obj/bootloader_main.o -o mooltipass_bootloader.elf -lm
-Wl,-Map=mooltipass_bootloader.map,--cref
-Wl,--gc-sections -Wl,--relax -mmcu=atmega32u4 -Werror
-Wl,--section-start=.text=0x7000 -Wl,--section-start=.spmfunc=0x7F80
-Wl,--undefined=spmfunc
/usr/lib/gcc/avr/4.9.2/../../../avr/bin/ld: section .spmfunc loaded at
[0000000000007f80,0000000000007fff] overlaps section .text loaded at
[0000000000007000,000000000000804f]

Unless I am missing something in documentation, I believe I am correctly
attempting to build for the MP mini and am attempting to do so correctly.

I will continue to investigate this, but after a couple of hours I am still
no closer to understanding what is going on.
Step by step guide to reproduce the problem

This was achieved with avr-gcc version 4.9.2 on 64bit Ubuntu Xenial 16.04
installed from apt.
Navigate to source_code/ or souce_code/src/ as noted above and attempt to
run 'make' with the BOOTLOADER = true option set in the makefile.
Mooltipass version

Not really applicable. I have a couple of mini's I've built from scratch
that I am intending to do some testing on. Am attempting to run through the
bootstrapping process you have. Documentation is pretty limited, but I
believe I am on the right track.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/limpkin/mooltipass/issues/348>, or mute the thread

**Comment by kbembedded** [comment]
I was unsure if you meant define MINI_BOOTLOADER in the context of a makefile variable, or adding it to DEFINES so CFLAGS have -DMINI_BOOTLOADER.

I tried doing both of the above, for both the makefile in source_code/ and source_code/src/ and the same problems arose.  Though, the resulting binary from source_code/ ended up being smaller by about 40 bytes.

**Comment by limpkin** [comment]
Hmm that's quite odd indeed.

May I ask, if you have the time, to double check the flags set compared to the following output?
Particularly the -mcall-prologues & -no-startfiles

Build started.
Project "bootloader_mini.cproj" (default targets):
Target "PreBuildEvent" skipped, due to false condition; ('$(PreBuildEvent)'!='') was evaluated as (''!='').
Target "CoreBuild" in file "C:\Program Files (x86)\Atmel\Studio\7.0\Vs\Compiler.targets" from project "C:\mooltipass\source_code\bootloader_mini.cproj" (target "Build" depends on it):
	Task "RunCompilerTask"
		Shell Utils Path C:\Program Files (x86)\Atmel\Studio\7.0\shellUtils
		C:\Program Files (x86)\Atmel\Studio\7.0\shellUtils\make.exe all --jobs 8 --output-sync 
		Building file: ../src/SPI/spi.c
		Invoking: AVR/GNU C Compiler : 4.9.2
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe"  -x c -mcall-prologues -funsigned-char -funsigned-bitfields -DNDEBUG -DF_CPU=16000000UL -DMINI_BOOTLOADER  -I"../src" -I"../src/AES" -I"../src/CARD" -I"../src/FLASH" -I"../src/LOGIC" -I"../src/NODEMGMT" -I"../src/OLEDMINI" -I"../src/OLEDMP" -I"../src/SPI" -I"../src/USB" -I"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\include"  -Os -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -Wall -Wextra -Werror -mmcu=atmega32u4 -B "C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\gcc\dev\atmega32u4" -c -std=gnu99 -MD -MP -MF "src/SPI/spi.d" -MT"src/SPI/spi.d" -MT"src/SPI/spi.o"   -o "src/SPI/spi.o" "../src/SPI/spi.c" 
		Finished building: ../src/SPI/spi.c
		Building file: ../src/AES/aes256_ctr.c
		Invoking: AVR/GNU C Compiler : 4.9.2
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe"  -x c -mcall-prologues -funsigned-char -funsigned-bitfields -DNDEBUG -DF_CPU=16000000UL -DMINI_BOOTLOADER  -I"../src" -I"../src/AES" -I"../src/CARD" -I"../src/FLASH" -I"../src/LOGIC" -I"../src/NODEMGMT" -I"../src/OLEDMINI" -I"../src/OLEDMP" -I"../src/SPI" -I"../src/USB" -I"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\include"  -Os -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -Wall -Wextra -Werror -mmcu=atmega32u4 -B "C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\gcc\dev\atmega32u4" -c -std=gnu99 -MD -MP -MF "src/AES/aes256_ctr.d" -MT"src/AES/aes256_ctr.d" -MT"src/AES/aes256_ctr.o"   -o "src/AES/aes256_ctr.o" "../src/AES/aes256_ctr.c" 
		Finished building: ../src/AES/aes256_ctr.c
		Building file: ../src/FLASH/flash_mem.c
		Invoking: AVR/GNU C Compiler : 4.9.2
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe"  -x c -mcall-prologues -funsigned-char -funsigned-bitfields -DNDEBUG -DF_CPU=16000000UL -DMINI_BOOTLOADER  -I"../src" -I"../src/AES" -I"../src/CARD" -I"../src/FLASH" -I"../src/LOGIC" -I"../src/NODEMGMT" -I"../src/OLEDMINI" -I"../src/OLEDMP" -I"../src/SPI" -I"../src/USB" -I"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\include"  -Os -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -Wall -Wextra -Werror -mmcu=atmega32u4 -B "C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\gcc\dev\atmega32u4" -c -std=gnu99 -MD -MP -MF "src/FLASH/flash_mem.d" -MT"src/FLASH/flash_mem.d" -MT"src/FLASH/flash_mem.o"   -o "src/FLASH/flash_mem.o" "../src/FLASH/flash_mem.c" 
		Finished building: ../src/FLASH/flash_mem.c
		Building file: ../src/bootloader_main.c
		Invoking: AVR/GNU C Compiler : 4.9.2
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe"  -x c -mcall-prologues -funsigned-char -funsigned-bitfields -DNDEBUG -DF_CPU=16000000UL -DMINI_BOOTLOADER  -I"../src" -I"../src/AES" -I"../src/CARD" -I"../src/FLASH" -I"../src/LOGIC" -I"../src/NODEMGMT" -I"../src/OLEDMINI" -I"../src/OLEDMP" -I"../src/SPI" -I"../src/USB" -I"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\include"  -Os -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -Wall -Wextra -Werror -mmcu=atmega32u4 -B "C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\gcc\dev\atmega32u4" -c -std=gnu99 -MD -MP -MF "src/bootloader_main.d" -MT"src/bootloader_main.d" -MT"src/bootloader_main.o"   -o "src/bootloader_main.o" "../src/bootloader_main.c" 
		Finished building: ../src/bootloader_main.c
		Building file: ../src/AES/aes.c
		Invoking: AVR/GNU C Compiler : 4.9.2
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe"  -x c -mcall-prologues -funsigned-char -funsigned-bitfields -DNDEBUG -DF_CPU=16000000UL -DMINI_BOOTLOADER  -I"../src" -I"../src/AES" -I"../src/CARD" -I"../src/FLASH" -I"../src/LOGIC" -I"../src/NODEMGMT" -I"../src/OLEDMINI" -I"../src/OLEDMP" -I"../src/SPI" -I"../src/USB" -I"C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\include"  -Os -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -Wall -Wextra -Werror -mmcu=atmega32u4 -B "C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\gcc\dev\atmega32u4" -c -std=gnu99 -MD -MP -MF "src/AES/aes.d" -MT"src/AES/aes.d" -MT"src/AES/aes.o"   -o "src/AES/aes.o" "../src/AES/aes.c" 
		Finished building: ../src/AES/aes.c
		Building target: bootloader_mini.elf
		Invoking: AVR/GNU Linker : 4.9.2
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe" -o bootloader_mini.elf  src/AES/aes.o src/AES/aes256_ctr.o src/bootloader_main.o src/FLASH/flash_mem.o src/SPI/spi.o   -nostartfiles -Wl,-Map="bootloader_mini.map" -Wl,--start-group -Wl,-lm  -Wl,--end-group -Wl,--gc-sections -mrelax -Wl,-section-start=.text=0x7000 -Wl,-section-start=.spmfunc=0x7f80  -mmcu=atmega32u4 -B "C:\Program Files (x86)\Atmel\Studio\7.0\Packs\atmel\ATmega_DFP\1.0.106\gcc\dev\atmega32u4"  
		Finished building target: bootloader_mini.elf
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-objcopy.exe" -O ihex -R .eeprom -R .fuse -R .lock -R .signature -R .user_signatures  "bootloader_mini.elf" "bootloader_mini.hex"
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-objcopy.exe" -j .eeprom  --set-section-flags=.eeprom=alloc,load --change-section-lma .eeprom=0  --no-change-warnings -O ihex "bootloader_mini.elf" "bootloader_mini.eep" || exit 0
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-objdump.exe" -h -S "bootloader_mini.elf" > "bootloader_mini.lss"
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-objcopy.exe" -O srec -R .eeprom -R .fuse -R .lock -R .signature -R .user_signatures "bootloader_mini.elf" "bootloader_mini.srec"
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-size.exe" "bootloader_mini.elf"
		   text	   data	    bss	    dec	    hex	filename
		   4048	      0	      0	   4048	    fd0	bootloader_mini.elf
	Done executing task "RunCompilerTask".
	Using "RunOutputFileVerifyTask" task from assembly "C:\Program Files (x86)\Atmel\Studio\7.0\Extensions\Application\AvrGCC.dll".
	Task "RunOutputFileVerifyTask"
				Program Memory Usage 	:	3920 bytes   12,0 % Full
				Data Memory Usage 		:	0 bytes   0,0 % Full
	Done executing task "RunOutputFileVerifyTask".
Done building target "CoreBuild" in project "bootloader_mini.cproj".
Target "PostBuildEvent" skipped, due to false condition; ('$(PostBuildEvent)' != '') was evaluated as ('' != '').
Target "Build" in file "C:\Program Files (x86)\Atmel\Studio\7.0\Vs\Avr.common.targets" from project "C:\mooltipass\source_code\bootloader_mini.cproj" (entry point):
Done building target "Build" in project "bootloader_mini.cproj".
Done building project "bootloader_mini.cproj".

Build succeeded.
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by kbembedded** [comment]
It would appear that extraneous files are being built here, namely:  
flash_test
aes256_nessie_test
aes256_ctr_test

It also looks like these were addressed and removed in PR #209 for the DMBS makefile in source_code/src/

I'll play with this more tomorrow and drop a note here with what I find.

I presume that windows with Atmel Studio is the now preferred build method?

**Comment by limpkin** [comment]
Right, we indeed have 2 different makefiles (I personally prefer the one you are using).
The 3 files you mention are not needed, you may therefore remove them from the makefile and make a PR if you feel like it.
There is no preferred build method, but the atmel studio solution is the one that has been more often used.

**Comment by limpkin** [comment]
Hello,

What's your current status? Is the problem solved?

**Comment by kbembedded** [comment]
I've been able to build a bootloader, was going to leave this open until I finalized a Makefile change and put in a PR.  Been a busy week so it may be a little while before I get to it.  I've found that even with similar options, the Atmel Studio built binary is still slightly smaller.  avr-gcc builds a binary that just squeaks by under the 4kbyte limit used in the python scripts.  I havn't looked in to them enough to know how important or significant that number is, I've also never really done anything with an AVR so I don't fully know all of the tricks that are used.

**Comment by limpkin** [comment]
glad you managed to make it work!
Actually sometimes the order in which the files are compiled can lead to different hex sizes...

**Comment by limpkin** [comment]
Hello there!
Could you quickly let me know the changes you made so I can update the repo, or better yet make a PR?
If you want I have some non numbered aluminum cases laying around that I could send you just for the shipping fee!

**Comment by kbembedded** [comment]
Apologies.  I am waiting to submit a PR until I get something working.  I'm having issues with the display I have and have not had time to verify everything is functional.  I don't want to end up building the bootloader wrong and have it cause other problems.  However, below is a patch of what is working so far to build the bootloader on linux that comes in at a smaller size.  This is the non-dmbs build system.

I appreciate the offer for some cases.  Shoot me an email at kris@kbembedded.com with some more details.

diff --git a/source_code/Makefile b/source_code/Makefile
index 143e9ee..0eb8528 100644
--- a/source_code/Makefile
+++ b/source_code/Makefile
@@ -50,11 +50,11 @@ TARGET  := mooltipass_bootloader
 OBJECTS := $(patsubst src/%.c,build/%.o, src/bootloader_main.c)
 LIBDIRS := $(addprefix src/, GUI CARD FLASH USB SPI OLEDMP UTILS AES NODEMGMT RNG PWM TOUCH LOGIC OLEDMINI)
 OBJDIRS := $(patsubst src/%.c,build/%.o, $(addprefix src/, FLASH SPI AES))
-LIBOBJS := $(foreach lib, $(OBJDIRS), $(patsubst src/%.c,build/%.o, $(wildcard $(lib)/*.c)))
+LIBOBJS := $(foreach lib, $(OBJDIRS), $(patsubst src/%.c,build/%.o, $(filter-out src/AES/aes256_ctr_test.c src/FLASH/flash_test.c src/AES/aes256_nessie_test.c, $(wildcard $(lib)/*.c))))
+DEFINES += MINI_BOOTLOADER
 
 # Special bootloader flags
-CC_FLAGS     += -DBOOT_START_ADDR=$(BOOT_START_OFFSET)
-LD_FLAGS     += -Wl,--section-start=.text=$(BOOT_START_OFFSET) $(BOOT_API_LD_FLAGS)
+LDFLAGS     += -Wl,--section-start=.text=$(BOOT_START_OFFSET) $(BOOT_API_LD_FLAGS) -nostartfiles
 
 # Flash size and bootloader section sizes of the target, in KB. These must
 # match the target's total FLASH size and the bootloader size set in the
@@ -82,7 +82,7 @@ MCU     := atmega32u4
 # Set CONFIG=DEBUG in the shell from which you invoke make to build a debug
 # build.
 CONFIG  ?= RELEASE
-DEFINES := F_CPU=16000000UL F_USB=16000000UL
+DEFINES += F_CPU=16000000UL F_USB=16000000UL
 #DEFINES := F_CPU=16000000UL F_USB=16000000UL MOOLTIPASS_VERSION="\"$(VERSION)\""
 
 CFLAGS  += -Wall -mmcu=$(MCU) -funsigned-char -funsigned-bitfields -fpack-struct

**Comment by kbembedded** [comment]
Apologies.  I am waiting to submit a PR until I get something working.  I'm having issues with the display I have and have not had time to verify everything is functional.  I don't want to end up building the bootloader wrong and have it cause other problems.  However, below is a patch of what is working so far to build the bootloader on linux that comes in at a smaller size.  This is the non-dmbs build system.

I appreciate the offer for some cases.  Shoot me an email at kris@kbembedded.com with some more details.

```
diff --git a/source_code/Makefile b/source_code/Makefile
index 143e9ee..0eb8528 100644
--- a/source_code/Makefile
+++ b/source_code/Makefile
@@ -50,11 +50,11 @@ TARGET  := mooltipass_bootloader
 OBJECTS := $(patsubst src/%.c,build/%.o, src/bootloader_main.c)
 LIBDIRS := $(addprefix src/, GUI CARD FLASH USB SPI OLEDMP UTILS AES NODEMGMT RNG PWM TOUCH LOGIC OLEDMINI)
 OBJDIRS := $(patsubst src/%.c,build/%.o, $(addprefix src/, FLASH SPI AES))
-LIBOBJS := $(foreach lib, $(OBJDIRS), $(patsubst src/%.c,build/%.o, $(wildcard $(lib)/*.c)))
+LIBOBJS := $(foreach lib, $(OBJDIRS), $(patsubst src/%.c,build/%.o, $(filter-out src/AES/aes256_ctr_test.c src/FLASH/flash_test.c src/AES/aes256_nessie_test.c, $(wildcard $(lib)/*.c))))
+DEFINES += MINI_BOOTLOADER
 
 # Special bootloader flags
-CC_FLAGS     += -DBOOT_START_ADDR=$(BOOT_START_OFFSET)
-LD_FLAGS     += -Wl,--section-start=.text=$(BOOT_START_OFFSET) $(BOOT_API_LD_FLAGS)
+LDFLAGS     += -Wl,--section-start=.text=$(BOOT_START_OFFSET) $(BOOT_API_LD_FLAGS) -nostartfiles
 
 # Flash size and bootloader section sizes of the target, in KB. These must
 # match the target's total FLASH size and the bootloader size set in the
@@ -82,7 +82,7 @@ MCU     := atmega32u4
 # Set CONFIG=DEBUG in the shell from which you invoke make to build a debug
 # build.
 CONFIG  ?= RELEASE
-DEFINES := F_CPU=16000000UL F_USB=16000000UL
+DEFINES += F_CPU=16000000UL F_USB=16000000UL
 #DEFINES := F_CPU=16000000UL F_USB=16000000UL MOOLTIPASS_VERSION="\"$(VERSION)\""
 
 CFLAGS  += -Wall -mmcu=$(MCU) -funsigned-char -funsigned-bitfields -fpack-struct
```

**Comment by limpkin** [comment]
Thanks! I can definitely wait for the PR. I've sent you an email!

**Comment by NicoHood** [comment]
I've already proposed those changes in https://github.com/limpkin/mooltipass/pull/209/files#diff-4b524f7dab0d600b1d6e5b5c785a0f87R63

**Comment by limpkin** [comment]
well... thanks for jumping in!
