### ISSUE TITLE
udev_rules.txt needs one more step

### ISSUE THREAD

**Issue by zyphlar** [limpkin/mooltipass#350]
### Expected behavior

Instructions at https://www.themooltipass.com/udev_rule.txt allow device to connect.

### Actual behavior

In addition to the instructions, the user may also need to log off and log back on to make udev rules apply to the session.

### Step by step guide to reproduce the problem

1. Follow all instructions at https://www.themooltipass.com/udev_rule.txt
2. Observe some flickering in the Mooltipass App GUI but still appearing disconnected.
3. Try closing Chrome, try locking the session, note no improvement
4. Log off and log back in; observe the Mooltipass is now connected.

### Mooltipass version

v1.2_mini

**Comment by limpkin** [comment]
Hello there,
Did you try the "udevadm control --reload-rules" command specified?

**Comment by zyphlar** [comment]
Yep, it didn't seem to help. I repeated the steps two or three times, but
logging off is what instantly fixed it.

Maybe Chrome stayed running in the background?

**Comment by limpkin** [comment]
fair enough then... we have updated udev_rule.txt ! 
Thanks a lot for taking the time to let us know of this problem.
