### ISSUE TITLE
Mass-import passwords from software solutions e.g. KeePass

### ISSUE THREAD

**Issue by cons0l3** [limpkin/mooltipass#367]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
I have several hundred passwords in a password safe software solution e.g. Password Safe, KeePass, ... I want to export the list from my software solution and import it into the Mooltipass.

### Justification
It is very tidious to copy&paste several hundreds of passwords. A clean solution for mass importing is appreciated

### Workarounds
Copy&Paste...

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello!   
Please read our mini user manual.

**Comment by JBerkvens** [comment]
Hello, I've read the user manual but it didn't make it clear for me. Is this already possible and if so, where can I find how to do so?

**Comment by limpkin** [comment]
I'm afraid we didn't document it yet.
You may find the option in the advanced menu enabled by pressing Ctrl shift
f2

**Comment by nausicaea** [comment]
I'm sorry to drag up an old issue, but the shortcut Ctrl-Shift-F2 does not work on the MacOS moolticute app. Is there any other way to enable the advanced settings menu?

**Comment by limpkin** [comment]
Iirc you should use alt instead of Ctrl on Mac :)

**Comment by nausicaea** [comment]
It ended up being Cmd-Shift-F2 (don’t forget the Fn button to switch from media buttons to F-keys). Thanks!

> 16. jul. 2019 kl. 08:37 skrev Mathieu <notifications@github.com>:
> 
> Iirc you should use alt instead of Ctrl on Mac :)
>
