### ISSUE TITLE
Missing leading ^ character

### ISSUE THREAD

**Issue by Jeroen-Vdh** [limpkin/mooltipass#374]
Expected the password would be filled in correctly

It skipped the ^ as the first character of the password
I checked the password in the app and it's correctly saved on the Mooltipass.

Use a password that starts with ^

V1.2 #1163

**Comment by limpkin** [comment]
Hello,

I'm guessing this is happening during manual password recall? Have you correctly configured your keyboard layout in the settings tab?

**Comment by Jeroen-Vdh** [comment]
Hi

Yes that's when it happens.
Yes my layout is correct: fr_BE.

For example I made a new credential which I will let mooltipass enter here.
The password is: ^hello
Mooltipass prints: ĥello

With this new password, I noticed it does write the ^ but it should write a space after that so it's not used for the next letter.

In the credential manager I changed ^hello to ^ hello (so I added the extra space) and now it writes: ^hello like it should.

I don't mean anything wrong with it, I just want to point this out so you know this.

**Comment by limpkin** [comment]
Hello there,

Thanks for the feedback! I had no idea this happened for FR_BE... are you sure it may not also depend on personal settings on the computer? I personally use FR_FR and can have ^hello without any problem.

**Comment by Jeroen-Vdh** [comment]
Hi

You're welcome.
It looks like it has something to do with my pc (Ubuntu 16.04) because I have the same problem with FR_FR.

**Comment by limpkin** [comment]
Oh... that's very interesting!
As you can imagine it may get a tad complex if we start creating variants depending on the OS being used (except for MAC... sigh) as the mooltipass itself can't detect which OS it is connected to.

**Comment by Jeroen-Vdh** [comment]
Yes I can understand that, now I know a workarround I don't even really care about the bug.
You can be sure I'm still happy with my Mooltipasses.

**Comment by limpkin** [comment]
I'll definitely have to add it to our FAQ though! It's one of these things....
I'm very happy you're happy with your minis! let us know if you have any problem / suggestion :)
