### ISSUE TITLE
Chrome+extension+captcha

### ISSUE THREAD

**Issue by kbembedded** [limpkin/mooltipass#376]
### Expected behavior
Not freaking out like it is

### Actual behavior
Go to page with CAPTCHA, in my example, drobox.com which had not previously been added to my MP credentials.  Enter name, pw, and skip captcha input, and attempt to sign in.

The missed captcha seems to create a "credential request" about once a second on the extension and MP itself.  I get the chrome popups continually until I disconnect MP and reload the page.  Trying to cancel the request on the MP just blinks with another one immediately after.

### Step by step guide to reproduce the problem
See behavior as steps are included.

### Mooltipass version
Which Mooltipass do you use? MPmini, home built from git resources
What is its firmware version? 1.2 (stock POST_KICKSTARTER_SETUP build with one or two other #defines to disable unused features.)

**Comment by limpkin** [comment]
@Gastonius : could you look into this? :)

**Comment by limpkin** [comment]
hello,  
Could you install the extension from source and make sure this behavior disappeared?
thanks

**Comment by limpkin** [comment]
solved in .85
