### ISSUE TITLE
Add support for Swedish keyboard layout

### ISSUE THREAD

**Issue by Jyx** [limpkin/mooltipass#378]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Add  `sv_SE` (Swedish keyboard support) to the the Chrome App under `Keyboard Output` -> `Configured keyboard layout`.

### Justification
Without the Swedish support the Mooltipass mini will (almost) always give incorrect username, since `en_US` gives a `"` symbol when it should enter the `@` sign. Example:
```
Username: john.doe@foo.bar
```
becomes
```
Username: john.doe"foo.bar
```

And as you can imagine, passwords will in some cases also be affected to this.

### Workarounds
Manually replace the characters before pressing the login button.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello,

If I remember correctly, SV_SE is exactly the same as FI_FI... could you try?

Thanks

**Comment by Jyx** [comment]
Hi,

I've never thought about that, but you're probably right. I've switched to `fi_FI` and it definitely behaves much better than `en_US`. After changing to `fi_FI` I've tried a handful of my stored logins (all unique and long passwords) and so far the output from Mooltitool was correct. So, for me and for now this is sufficient.

Will this be the final solution? Or do you anyway plan to add `sv_SE`? The reason for asking is whether I shall close this issue or not.

**Comment by limpkin** [comment]
I think I remember creating the sv_se layout a few years ago, and running a
binary compare just to find that it was exactly the danger as fi_fi.
So I think you can close the issue.

**Comment by Jyx** [comment]
Alright, thanks for the quick turn around time.
