### ISSUE TITLE
new issues logging in with mooltipass

### ISSUE THREAD

**Issue by ReonBalisty** [limpkin/mooltipass#385]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
logging in properly

### Actual behavior
not entering the password field at all.

being prompted twice for entering the data via the hardware.

### Step by step guide to reproduce the problem
when prompted to enter in credentials via mooltipass hardware, press button, only enters the email field and prompts twice.
(I have tried it with both mooltipass extensions running separately.
sites tried:
facebook.com
github.com

### Mooltipass version
1? original Indiegogo firmware
2.0.69 mooltipass app
1.1.76 mooltipass extension (ffe)
1.1.76 mooltipass extension (mkj id)
8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello,

I'm not sure to understand you correctly.
Are you using the chrome app or mooltiapp? What do you mean by "I have tried it with both mooltipass extensions running separately." ?
I've just tried facebook & github, without any problem

**Comment by ReonBalisty** [comment]
Google Chrome version 58.0.x.x.x.x.x(just checked for update, none)
![proofofex](https://cloud.githubusercontent.com/assets/8903224/25307067/a74f4cd0-274f-11e7-8219-b7ab7159dff0.jpg)
![proofofex1](https://cloud.githubusercontent.com/assets/8903224/25307068/a750ba84-274f-11e7-8d16-e100ee6fc50e.jpg)
No password is being entered
The extension seems to not be entering the data or not "tabbing" to the next line to enter the data.

**Comment by ReonBalisty** [comment]
And as stated is clearly prompting me twice via the hardware (mooltipass display) to enter the data twice, and or confirmation of entering the data into the credential field.

**Comment by limpkin** [comment]
Hello,

When you say "twice": what happens when you approve the first time on the device? could you give us a detailed description of what you do and what happens?

**Comment by ReonBalisty** [comment]
Mooltipass App 2.0.69 enabled the whole time.
A.
1.With the extension enabled (id FFE)
2.device prompts
3. authorize the prompt
4. the software enters only the email into the email field
5. then, prompts with the same screen display again on the device.
6. authorize again, same result as step 4

B.
1. extension enabled (id MKJ) and the other extension disabled
repeats A. 2-6

**Comment by limpkin** [comment]
Thanks for the description! 
We've been having a similar bug for Kickstarter, but without the double prompts. We'll try to investigate why this happens on some computers and not on others.
@Gastonius

**Comment by ReonBalisty** [comment]
Windows 7 Ultimate sp 1

**Comment by ReonBalisty** [comment]
A second prompt on the mooltipass occurs even if logging in works.

**Comment by limpkin** [comment]
Hello there,  
I've just pushed .77 to our testers-only extension. Could you uninstall your current extension and install this one:  https://chrome.google.com/webstore/detail/mkjlelalgdinanmcljpgkojjolkdcebh and then let me know if it solved your problems?

**Comment by ReonBalisty** [comment]
Pushed and works, thanks, @limpkin.

**Comment by limpkin** [comment]
wonderful! I was hoping my bug was connected to yours.
