### ISSUE TITLE
Support credential storage/recall when using non standard ports

### ISSUE THREAD

**Issue by limpkin** [limpkin/mooltipass#390]
From a kickstarter backer:

"It seems that I only get asked to add a new service when the website runs with normal http/https port. I would like to add my passwords of my local development machine which runs with port 8080. The password fields have that key symbol and manually adding the username / pw field does not seem to work"

**Comment by kbembedded** [comment]
I too experience this, it would definitely be a nice to have.

**Comment by RChadwick7** [comment]
I have similar issues. I have a number of services on a number of ports (IP Cameras, Nextcloud install, etc), and have problems with the Firefox plugin not differentiating between websites with the same IP or domain name, but different ports.

**Comment by limpkin** [comment]
will be pushed in extension .85
