### ISSUE TITLE
$ displayed as ç

### ISSUE THREAD

**Issue by pascalwacker** [limpkin/mooltipass#392]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
When the password contains a `$` it should be outputed as `$`

### Actual behavior
`$` is outputed as `ç`

### Step by step guide to reproduce the problem
Set the keyboard layout to `de_DE` in the app (as there's no de_CH)

Save a password containing a `$` sign and output it in a text editor (it shows `$` in the Mooltipass app, but `ç` in a text editor).

The issue is acctually, that there is no support for de_ch keyboards:
de_de layout: https://en.wikipedia.org/wiki/File:KB_Germany.svg
de_ch layout: https://upload.wikimedia.org/wikipedia/commons/4/4f/KB_Swiss.svg

If I could help to add the de_ch layout, let me know, I'd love to help.

### Mooltipass version
Mooltipass Mini (v1.2 #1412)

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello,

Please select frde_CH.

**Comment by pascalwacker** [comment]
@limpkin works like a charm! Thanks (: (I would still recommend to rename it to `de_CH`, as I just checked the locales starting with `de_`)

**Comment by limpkin** [comment]
but it wouldn't be fair to the suisses romands ;)

**Comment by pascalwacker** [comment]
If they are the same, then agreed. I always assumed, the `fr_CH` keyboard would be slightly different. In the case that they are the same, how about adding both options `fr_CH` and `de_CH` pointing to the same layout?

Completely off topic, but since you are the owner of the git repo, you might know this: Is there a way to import all saved logins from the firefox password manager? So far I haven't found anything adressing this.

**Comment by limpkin** [comment]
Thanks for the suggestion.
Have you looked at the CSV Import feature inside our user manual?

**Comment by pascalwacker** [comment]
Not yet, but I will now ;) Thanks for your help and very quick response!
