### ISSUE TITLE
Device doesn't show up in App on Ubuntu 16.04

### ISSUE THREAD

**Issue by pascalwacker** [limpkin/mooltipass#393]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Mooltipass to show up in app on Ubuntu 16.04

### Actual behavior
App shows "Connect your Mooltipass device" screen

### Step by step guide to reproduce the problem
Installed the 64bit .deb app from https://www.themooltipass.com/setup on a Ubuntu 16.04, 64bit laptop and connected mooltipass using the provided USB cable. The device it self works and can be used to fill in logins on websites! The same device works without problems on my win10 machine, so I'm guessing the problem is somewhere in ubuntu/the app

### Mooltipass version
Mooltipass Mini (v1.2 #1412)

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
please add the udev rules as described in our setup page.

**Comment by pascalwacker** [comment]
I can confirm that `gpasswd -a myuser plugdev` and `echo "ATTRS{idVendor}==\"16d0\", ATTRS{idProduct}==\"09a0\", SYMLINK+=\"mooltipass\", MODE=\"0664\", GROUP=\"plugdev\"" > /etc/udev/rules.d/50-mooltipass.rules` and loging out and in again, worked on my Ubuntu 16.04.

As a suggestion: Put a link to the [solution](https://www.themooltipass.com/udev_rule.txt) below the download link at the setup page, that way, it hopefully won't be missed or even better, include that command in the setup process. Also maybe explain the commands, what they do, a little more, as not that experienced user could be afraid of commands they don't understand.

**Comment by limpkin** [comment]
thanks for the suggestion! we've added a link to the udev rule under the debian icon :)
