### ISSUE TITLE
Select custom credential fields dialog may show in the wrong chrome tab

### ISSUE THREAD

**Issue by nelabidi** [limpkin/mooltipass#395]
### Expected behavior
Click on "Select custom credential fields for this page" should show a dialog and it should select/highlight input fields in the window in the current tab where the user clicked on the extension icon in the browser. 

### Actual behavior
Click on "Select custom credential fields for this page"  option can act on the wrong tab 

### Step by step guide to reproduce the problem
- Open a chrome window and go to a website which you have no stored credential.
- Open another chrome window and go to the same website or another one which you have no stored credential
- No go back to the first window  and click on  "Select custom credential fields for this page"  option in mooltipass extension popup
- the second window now will show  a dialog and highlight input fields 

### Operating System
Mention if you are using either:
-  Windows 7, SP1, Chrome 57
  
Other operating systems are not supported.

### Mooltipass Extension
Mention if you are using either:
- the chrome extension:  latest from the repository , master branch

### Mooltipass Device
- multicute emulator

**Comment by nelabidi** [comment]
It's obvious that this issue is focus related and it's caused by relaying on 'set_current_tab' event and page.setCurrentTab handler to update page.currentTabId property used to identify which content script should we request to show "Select custom fileds" .  
A solution is to use tabs.query, something like `chrome.tabs.query({active: true, currentWindow: true}, function(tab) {  // use tab object here tab.id});`

**Comment by hawk-lord** [comment]
Here is a fix to put in init.js, somewhere at line 75:
```
/**
 * Set active tab if switched to another window.
 */
chrome.windows.onFocusChanged.addListener(function() {
	chrome.tabs.query({active: true, lastFocusedWindow: true}, function(tabs) {
		if (tabs && tabs[0] && tabs[0].id) {
			page.currentTabId = tabs[0].id;
			if(tabs[0].status === "complete") {
				event.invoke(page.switchTab, null, tabs[0].id, []);
			}
		}
	});
});

```
