### ISSUE TITLE
Basic authentication not handled by Mooltipass (Firefox, over https)?

### ISSUE THREAD

**Issue by e-dot** [limpkin/mooltipass#404]
### Expected behavior

Automatic completion of login/password for web sites using basic http authentication (over https/TLS), with Firefox Web Browser.

### Actual behavior

Firefox asks for login/password with the authentication dialog box - but Mooltipass is not notified and does not provide login/password.

### Operating System
- Debian Based Distribution (Ubuntu 16.04)
  
### Mooltipass Extension

Using the firefox extension 1.1.79

### Mooltipass Application
- MooltiApp on Linux (latest version).

### Mooltipass Device

The Mooltipass Mini

**Comment by limpkin** [comment]
Hello there,
Thanks for bringing this to our attention. This was only tested with chrome and not firefox.
We'll get on it hopefully this month.

**Comment by e-dot** [comment]
Ok thank you. Is there any way I could help on this? is the extension source code available - and where?

Regards,

E.

**Comment by limpkin** [comment]
of course! that would be really appreciated.
extension folder is here: https://github.com/limpkin/mooltipass/tree/master/chrome_extension

**Comment by limpkin** [comment]
Hello!
Out of curiosity, did you make any progress?

**Comment by reepush** [comment]
@e-dot Hi! Check out new version, http auth is supported now.

**Comment by limpkin** [comment]
closing issue.
