### ISSUE TITLE
[Question]How to migrate from Old / Legacy Keycard to Mini Key Card?

### ISSUE THREAD

**Issue by Frankstar** [limpkin/mooltipass#407]
Title says it all.

i didnt found a solution.

**Comment by limpkin** [comment]
Hello,

The github repo is not the place to ask these questions.

On mooltipass original:
- insert card
- open the app
- make a backup
On mooltipass mini
- insert card
- get "unknown card" screen
- open app, select backup file
- make a clone of your card to a mini card
