### ISSUE TITLE
Mooltipass not working from within virtual machine (VMWare Workstation 12)

### ISSUE THREAD

**Issue by e-dot** [limpkin/mooltipass#408]
### Expected behavior

Use mooltipass in a virtual machine : plug the mooltipass in a host system, and use it from the guest system (like you can do with USB Keys, drives, keyboards, etc...)

### Actual behavior

Mooltipass not seen by VMWare Workstation - and can't be plugged into a virtual machine.

### Operating System

- Windows 10 on virtual machine (guest)
- Ubuntu 16.04 on host with VMWare Workstation 12
  
### Mooltipass Extension

Any.

### Mooltipass Application

Any.

### Mooltipass Device
- The Mooltipass Mini

**Comment by limpkin** [comment]
Hello,
Are you 100% sure? **All** of our cross platform tests are done using virtual machines.

**Comment by e-dot** [comment]
Well I may have a different configuration - host running linux ubuntu 16 + vmware workstation ; are you using the same king of virtualization software?

**Comment by limpkin** [comment]
did you add the correct udev rules?

**Comment by e-dot** [comment]
I think so - the mooltipass is recognized and is working from the linux host. But it's not seen from VMWARE Workstation (and can't be "plugged" into the virtual machine, unlike a regular USB key).

**Comment by limpkin** [comment]
working.... with what? chrome app / mooltiapp / moolticute?
a few links worth checking out:
- https://communities.vmware.com/thread/169277
- https://pubs.vmware.com/workstation-9/index.jsp?topic=%2Fcom.vmware.ws.using.doc%2FGUID-07883F0A-E7B5-4CBA-837D-0BA986E8B900.html

**Comment by e-dot** [comment]
On the host - working with Firefox and Mooltiapp.
I'll check the article to see if they provide a workaround.

**Comment by limpkin** [comment]
I'll close the issue as this is not related to the mooltipass software or hardware.
