### ISSUE TITLE
ctrl-l-i-m does not work on ChromeBook

### ISSUE THREAD

**Issue by frankenstein91** [limpkin/mooltipass#411]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Make the other Tab visible

### Actual behavior
nothing 

### Step by step guide to reproduce the problem
open Chrome
go to the extension
open mooltipass app
press ctrl-l-i-m

### Operating System
ChromeOS
  
### Mooltipass Extension
Mooltipass Extension 1.1.80

### Mooltipass Application
Mooltipass App 2.0.78

### Mooltipass Device
The Mooltipass Mini

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
at the end of ctrl-l-i-m, all 4 keys need to be pressed.

**Comment by frankenstein91** [comment]
thank you
please add it to the read me
