### ISSUE TITLE
can't remove website from blacklist

### ISSUE THREAD

**Issue by frankenstein91** [limpkin/mooltipass#414]
### Expected behavior
have something to remove URL from blacklist

### Actual behavior
can only view and add to black list

### Step by step guide to reproduce the problem
add a URL to blacklist 
go to Extension settings
go to blacklist

### Operating System
ChromeOS

### Mooltipass Extension
Mooltipass Extension 1.1.80

### Mooltipass Application
Mooltipass App 2.0.78

### Mooltipass Device
The Mooltipass Mini

**Comment by limpkin** [comment]
this bug has been fixed in https://github.com/limpkin/mooltipass/commit/334fb1c6390bc23c8d169616038e9265405eeeeb

**Comment by frankenstein91** [comment]
how do I get the update?
Chrome does not show a update for the Extension.

**Comment by limpkin** [comment]
we haven't published it yet as there's still the "select custom credential fields bug"

**Comment by frankenstein91** [comment]
do you know a workaround to solve it for one url?

2017-05-19 16:07 GMT+02:00 Mathieu <notifications@github.com>:

**Comment by limpkin** [comment]
well in the settings open the chrome extension settings page, go to the blacklisted websites, go on the right of the url, click on the square.

**Comment by frankenstein91** [comment]
there is no square or something else
![screenshot 2017-05-19 at 16 10 47](https://cloud.githubusercontent.com/assets/2527348/26251514/ce14ad56-3cad-11e7-9f8d-a40d0c02f8ff.png)

**Comment by limpkin** [comment]
put your mouse on the website line, it'll appear

**Comment by frankenstein91** [comment]
no it only change the color of the background

**Comment by limpkin** [comment]
![image](https://cloud.githubusercontent.com/assets/6170291/26251694/6d360736-3cae-11e7-9e6a-1e4581734fd2.png)

**Comment by frankenstein91** [comment]
![screenshot 2017-05-19 at 16 16 37](https://cloud.githubusercontent.com/assets/2527348/26251741/964a91be-3cae-11e7-96c8-498dbcbb7dda.png)
This line is not clickable, tried it before opening the issue

**Comment by limpkin** [comment]
ok... then no workaround i'm afraid.

**Comment by frankenstein91** [comment]
Update to 1.1.82 and still not possible

**Comment by limpkin** [comment]
damn it.... can you use the extension menu to remove from blacklist?

**Comment by frankenstein91** [comment]
yes, but not over the item list.
Thank you for the tipp.

Could you please tell me if it is possible to blacklist a folder of a website not the domain?

**Comment by limpkin** [comment]
what do you mean by folder of a website?

**Comment by frankenstein91** [comment]
Like https://github.com/limpkin/mooltipass/ and not https://github.com/.
Because I have a domain with /blog and /someothertool and do not use the mooltipass for someothertool. 
This is how I get in to this problem, because I tried what url is saved in the blacklist. In the test my domain was blacklisted and until today it was not possible to remove it

**Comment by limpkin** [comment]
Oh, I see. I'm afraid that at the moment it is not possible.

**Comment by frankenstein91** [comment]
but here is a new screenshot from chromeos blacklist
![screenshot 2017-05-30 at 10 03 29](https://cloud.githubusercontent.com/assets/2527348/26573801/5bc1ad56-451f-11e7-8298-8110aa581f93.png)

**Comment by limpkin** [comment]
fixed in #451 , will be pushed to testers in the coming days.
