### ISSUE TITLE
Tweaking the sensitivity of knock detection.

### ISSUE THREAD

**Issue by RChadwick7** [limpkin/mooltipass#416]
Currently, knocking to approve password sending does not work at all for me. As I have a laptop on a small desk on a moveable arm, there is probably a lot of mechanical noise the sensor is filtering out. It also appears the frequency response might need to be tweaked. 
I keep the sensitivity setting on low. However, it seems to reliably recognize a cellphone that vibrates when it's on the same desk (A potential security issue.. If a cellphone is near the Mooltipass, one can approve sending credentials remotely simply by sending a text to the phone, and the vibration notification would be confused for a knock). However, when I actually try to knock, it almost always is not accepted. My guess is that there may be an automatic gain control function that may leave the Mooltipass deaf to a knock, or perhaps too many detected 'knocks' leave the unit unable to isolate two. However, if I go out of my way to keep everything extremely still, it will detect a slight tap, even on the lowest sensitivity. I have tried tapping directly on the unit, but never got that to work. If the sensor could filter out higher frequency sounds, such as a vibrator on a phone, but respond to a 2Hz double knock, it could more accurately detect knocks. Having additional sensitivity settings with less sensitivity may also help functionality. Finally, for diagnostic purposes, it would be extremely helpful if there was a feature that would display something when the Mooltipass thought it detected a knock.

I don't know if this is relevant. I once spent nearly a month developing a movement sensor with a mechanical engineer. While he had fancy simulation software that did awesome frequency analysis, he never could understand the difference between motion and sound, and he kept designing a more and more efficient microphone using a piezo element. It didn't detect motion, but would have false triggered on everything. I basically put a weight on an end of the piezo, and it bent during motion. He couldn't understand how it worked.

**Comment by limpkin** [comment]
Hello there!

I'll have a new setting added to our application then.
