### ISSUE TITLE
Chrome Extension issues with older Mooltipass

### ISSUE THREAD

**Issue by ReonBalisty** [limpkin/mooltipass#417]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
The mooltipass to actually register and be usable in the asking for credentials.

### Actual behavior
Mooltipass Application is not even registering as working for automatic (doesn't ask the mooltipass display to have it enter your credentials). Red inner circle on the app extension interface in Google Chrome as it states to "Please connect your mooltipass" tried all 10 different USB slots including 2 USB 3.0 slots just for giggles. To my dismay, this did not change the issue.

### Step by step guide to reproduce the problem
See above

### Operating System
Mention if you are using either:
- Windows 7
  

### Mooltipass Extension
Mention if you are using either:
- the chrome extension: 1.1.81

### Mooltipass Application
Mention if you are using either:
- the chrome application: 2.0.79

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Standard

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello,
What does the chrome app display? "please connect your device" or the standard tabs?

**Comment by ReonBalisty** [comment]
The chrome app display pop-out window just shows the mooltipass logo key with the rest blank

**Comment by ReonBalisty** [comment]
![image](https://cloud.githubusercontent.com/assets/8903224/26526446/5fb1f484-4330-11e7-9784-46f41e862514.png)

**Comment by limpkin** [comment]
Wow... that's unheard of.
Is there anything special installed on your computer? could you try uninstalling and reinstalling mooltiapp?

**Comment by ReonBalisty** [comment]
So I was going to uninstall and reinstall, and of course did do such moments ago, now it works, will open again if the same problem appears.

**Comment by limpkin** [comment]
great! let me know if this happens again :/
