### ISSUE TITLE
Backup to google account 

### ISSUE THREAD

**Issue by frankenstein91** [limpkin/mooltipass#421]
How is the export to a Google Account encrypted?
And what is needed to recover the backup?

**Comment by limpkin** [comment]
Hello,
What exactly do you mean?

**Comment by frankenstein91** [comment]
I would like to know how the export is stored at the google servers and which data is needed to recover the export back to a device. With data I mean something like a Pin or password.

**Comment by limpkin** [comment]
- you may see which data is stored by using our "export to file" button and opening the file
- to recover this data, a user must be logged in through his/her google account. The app will then check the multiple backup files on his google account for the currently inserted card unique ID

**Comment by frankenstein91** [comment]
To keep it simpel... no recovery without card?

**Comment by limpkin** [comment]
that is correct.
