### ISSUE TITLE
Jittery scroll wheel selection

### ISSUE THREAD

**Issue by oo-swoop-oo** [limpkin/mooltipass#423]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Scrolling with the wheel cycles through lists/selections smoothly. Each scroll wheel tick corresponds to an advancement to the next/previous selection.

### Actual behavior
Scrolling the wheel (even at slow rates or a-tick-at-a-time) periodically jumps from the currently selected item, either forward to the next selection or reverse to the previous selection on its own without having to interact with the scroll wheel.

### Step by step guide to reproduce the problem
1. Insert pass-card
3. On the lock screen where you enter your pass-card's pin begin scrolling the wheel through the hex characters for each pin position
4. Observe how the display behaves with each scroll wheel tick
5. Issue appears to occur 1 in 8 times (on average for me) the scroll wheel is turned

### Operating System
OSX
  
### Mooltipass Extension
Chrome extension v 1.1.82

### Mooltipass Application
Chrome app v 2.0.80

### Mooltipass Device
The Mooltipass Mini

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello there,

How new is your mini? We've noticed such behavior with very new units.

**Comment by oo-swoop-oo** [comment]
I received my Mooltipass Mini 1.0 earlier this month. If it helps, the serial number is MPM-2572.

On Jun 1, 2017 1:47 AM, Mathieu <notifications@github.com> wrote:

Hello there,

How new is your mini? We've noticed such behavior with very new units.

**Comment by limpkin** [comment]
right... I suggest that you come back to us in 2 weeks and if the problem persists, and we'll organize a standard exchange. would that be alright?

**Comment by oo-swoop-oo** [comment]
That's fair. Thanks.


On Jun 1, 2017 8:44 AM, Mathieu <notifications@github.com> wrote:

right... I suggest that you come back to us in 2 weeks and if the problem persists, and we'll organize a standard exchange. would that be alright?

**Comment by NicoHood** [comment]
I recently noticed a similar problem. After some weeks of use the wheel sometimes "goes crazy" and moves way to much steps for or backward. It happens randomly, but feels like a hardware defect. But its not critical, just annoying. And I think it is not me (as it wasnt there before) nor the software. I will report if it gets worse, just want to document this.

**Comment by jp-at-grantoo-org** [comment]
This is getting really frustrating.  I love the device but this issue is making it unusable. I have multiple minis and although I'm still waiting for the replacement to arrive, the issue is cropping up on my other minis.  It's at a point where it's only barely useable if I scroll the wheel very slowly (one tick per second), and even then it will sometimes advance or jump back to the previous item selection. Scrolling any faster than this results in the selection often going crazy.

Here's a link to a video I made of the scrolling action. Note that I'm only scrolling the wheel in the counter-clockwise direction.  I first start with scrolling one tick at a time, and then increase my scrolling speed:

https://vid.me/lD2BD

**Comment by jp-at-grantoo-org** [comment]
Playing around with the scroll wheel a bit more seems to indicate that at some point between scroll-ticks the device is unsure as to whether or not to scroll forward or backward - there is an intermediate position between scroll-ticks that has undefined/uncertain behaviour.  Not sure how this condition developed or is getting worse over time. Maybe the circuit contacts are starting to overlap?

**Comment by NicoHood** [comment]
I have the exact same issue and its also getting worse. Its on the Mooltipass that i have in daily use.

**Comment by limpkin** [comment]
Hello everyone,

As a reminder, simply send us a message at support[at]themooltipass.com and
we will have a replacement unit shipped to you.
