### ISSUE TITLE
Website SSL cert invalid

### ISSUE THREAD

**Issue by psypete** [limpkin/mooltipass#424]
### Expected behavior
Go to website, get a valid connection.

### Actual behavior
Insecure connection warning.

### Step by step guide to reproduce the problem
1. Go to https://www.themooltipass.com/ with any https client.
2. Get invalid TLS certificate warning.

### Operating System
Linux

### Mooltipass Extension
N/A

### Mooltipass Application
N/A

### Mooltipass Device
N/A

### Notes
psypete@windows:~$ curl -v https://www.themooltipass.com/ 2>&1 | grep -A6 "SSL c"
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL; CN=ssl17.ovh.net
*  start date: Sep 30 00:00:00 2016 GMT
*  expire date: Sep 30 23:59:59 2017 GMT
*  subjectAltName does not match www.themooltipass.com

**Comment by NicoHood** [comment]
Same issue here with firefox.

**Comment by limpkin** [comment]
holy sh*t I'm so tired of this host.
A couple of months ago it was partial content requests that simply stopped working, 2 months ago it was url rewritting, and now this.
Thanks for reporting... will have to disable https for now until they get their sh*t together

**Comment by limpkin** [comment]
https has been disabled... hopefully it'll be up and running tomorrow.

I'm speechless seeing how bad OVH are.

**Comment by NicoHood** [comment]
Which hoster do you use? Try:
https://www.gandi.net/

**Comment by limpkin** [comment]
https is back!
