### ISSUE TITLE
Browser extension for Pale Moon

### ISSUE THREAD

**Issue by targetdrone** [limpkin/mooltipass#426]
### Missing feature
Browser extension for Pale Moon

### Justification
As Firefox continues to diverge from the original path of an open source browser, Pale Moon becomes more appealing as an open source, high performance browser.  Many Firefox extensions work in Pale Moon without change, but the Mooltipass Extension does not (at least not in Pale Moon Version: 27.3.0 (64-bit)).

### Workarounds
The Mooltipass doesn't appear to be sending keystrokes into Pale Moon, even when the username or password field has focus.  The only workaround is to continue to use Firefox and the Firefox Mooltipass Extension.

**Comment by limpkin** [comment]
I'm afraid that won't happen because of their strategic choice with web extensions: https://forum.palemoon.org/viewtopic.php?t=15928
