### ISSUE TITLE
Two-Channel Auto-Type Obfuscation

### ISSUE THREAD

**Issue by alienfactor** [limpkin/mooltipass#427]
### Missing feature
Two-Channel Auto-Type Obfuscation

### Justification
Two-Channel Auto-Type Obfuscation makes standard keyloggers useless. It uses the Windows clipboard to transfer parts of the auto-typed text into the target application. 

Detailed information: http://keepass.info/help/v2/autotype_obfuscation.html

### Operating System
Windows

**Comment by NicoHood** [comment]
We do not have access to the clipboard from the device. I think the only way to obfuscate this is to type random characters at a random time and delete them afterwards. However you can track the delete keypress which will be too, so I dont think it could help. However a nice suggestion. Maybe someone else knows how to realize this.

**Comment by limpkin** [comment]
Nicohood is indeed right.
