### ISSUE TITLE
Question regarding bypassing pin entry limits 

### ISSUE THREAD

**Issue by anazmy** [limpkin/mooltipass#428]
Hi, 

How hard is it to go around the pin entry limitations? 

For example, using backup/restore approach to programmatically try millions of pin entries, considering its only 4 digit pin.

**Comment by limpkin** [comment]
Hello,

The card itself remembers the number of wrong tries, so I don't think your
question is valid....

**Comment by anazmy** [comment]
Thanks for the prompt reply, 

So in theory, you can't backup/restore  the card state in order to have unlimited trials, right ?

**Comment by limpkin** [comment]
Indeed.

**Comment by anazmy** [comment]
Thanks appreciate the brilliant work you're doing.

**Comment by limpkin** [comment]
Thanks a lot!
