### ISSUE TITLE
Issues while trying to log-in to sites with too long URI

### ISSUE THREAD

**Issue by moonwhaler** [limpkin/mooltipass#430]
### Expected behavior

Save credentials, login functionality.

### Actual behavior

Login not working (redirected to wrong URIs) with manually saved credentials. Maybe you should REALLY consider supporting longer fields (description, username, password (more than 31 chars), URI)

### Step by step guide to reproduce the problem

1. Calling (long) login URI
2. Entering credentials
3. No auto-popup (Chrome browser extension) _possibly due to long URI_
4. Manually saving the credentials via "key" symbol on password field
5. Logging off
6. Calling (long) URI again
7. Login notification on Mooltipass device & login
8. Redirection to wrong / error login page
9. Calling URI again - logged in

### Operating System

Windows 10
  
### Mooltipass Extension

Chrome extension: 1.1.82

### Mooltipass Application

Chrome application: 2.0.80

### Mooltipass Device

Mooltipass **Mini**

**Comment by limpkin** [comment]
Hello there,

We support 62chars URLs... could you give us the URL you are using?
Maybe it's simply because the extension isn't compatible (yet) with the website.

**Comment by moonwhaler** [comment]
Sure. One where this was happening (not a long URI) is 
https://www.vodafone.de/ussa/login/login.ftel

The other one being:
https://nordinary-com.netcup-mail.de/SOGo/so/

**Comment by limpkin** [comment]
From what I see this has nothing to do with long URL, but because we do not intercept the login & password and trigger an erroneous submit

**Comment by limpkin** [comment]
hello there,

could you uninstall your current extension, install the one that our testers use (https://chrome.google.com/webstore/detail/mooltipass-extension/mkjlelalgdinanmcljpgkojjolkdcebh?utm_source=chrome-app-launcher-info-dialog) and let us know if this now works for you?

Thanks

**Comment by moonwhaler** [comment]
I am using Mooltipass Extension 1.1.83 now, but it still doesn't work. The errors are exactly the same.

**Comment by reepush** [comment]
@moonwhaler 
There is still a problem with submitting form. Will fix soon and write back.

**Comment by limpkin** [comment]
hey there!
Could you try again? we've recently pushed 1.1.84 which should help.

**Comment by limpkin** [comment]
guys?
