### ISSUE TITLE
Move extension's UI to iframes

### ISSUE THREAD

**Issue by reepush** [limpkin/mooltipass#459]
Recently we had a problem with komoot.de – scripts on page prevented focus event and text field was unavailable in our password generation tooltip. Problems with different appearance on different sites are also known.

Little info about how it should work:
https://stackoverflow.com/questions/12783217/how-to-really-isolate-stylesheets-in-the-google-chrome-extension/25100953#25100953

We need to make communication between iframes and our scripts. Next I will count our UI elements and write them down here.

**Comment by reepush** [comment]
I discovered following UI in content script:
* Password icon
<img width="88" alt="screen shot 2017-08-07 at 12 45 13" src="https://user-images.githubusercontent.com/8476339/29021549-8b6816be-7b6e-11e7-9fc9-dc3f7ac60470.png">
* Password generation dialog
<img width="287" alt="screen shot 2017-08-07 at 12 47 49" src="https://user-images.githubusercontent.com/8476339/29021585-ab633688-7b6e-11e7-9e42-97dbfac677e7.png">
* Custom credential fields selection

**Comment by reepush** [comment]
Moving to #481.

**Comment by limpkin** [comment]
implemented.
