### ISSUE TITLE
Websites in local network won't be recognized

### ISSUE THREAD

**Issue by EidEchse** [limpkin/mooltipass#465]
### Expected behavior
Recognize local Websites like http://localhost:8080 or http://vmbuild:8080 as normal Websites and ask the Mooltipass for the credentials.

### Actual behavior
The user and password field at local network websites will be recognized but the credentials won't be requested or saved.

### Step by step guide to reproduce the problem
Call a website in the local network like a "Sonatype Nexus Repository" and try to login with the chrome app.

### Operating System
- Windows 7 64bit

### Browser
- Vivaldi (Chromium Engine) 1.10.867.38

### Mooltipass Extension
Chrome extension: 1.1.82
as well as in Firefox Extension 1.1.85

### Mooltipass Application
Mooltipass App: 2.0.81

### Mooltipass Device
- The Mooltipass Mini

**Comment by limpkin** [comment]
Hello there!
If I'm not mistaken localhost:8080 should work on the firefox 1.1.85... could you confirm?
In any case we'll get to that

**Comment by EidEchse** [comment]
- localhost:8080/admin
  - Chrome -
   - Firefox +
- vmbuild:8081/nexus/
  - Chrome -
  - Firefox -
- localhost:8080/
  - Chrome -
  - Firefox +

The Mooltipass Extension doesn't make a difference between localhost:8080/admin and localhost:8080 although its defined different in the Mooltipass:
![image](https://user-images.githubusercontent.com/3710207/28560670-f1b80288-711b-11e7-8cd6-e6253aa47770.png)

**Comment by limpkin** [comment]
Hello,

For the last point this is per design, as login URLs on standard websites
may change (think of get parameters).
We'll implement the fix for the vmbuild part on .86

**Comment by limpkin** [comment]
solved in latest 1.3.0 extension
