### ISSUE TITLE
sites compatibility

### ISSUE THREAD

**Issue by reepush** [limpkin/mooltipass#473]
* https://www.myplanrs.com/tf/myPLAN/SponsorWelcome
* https://secure.linkpt.net/lpc/servlet/LPCLogin
* https://secure.mercbank.com/MercantileBankofMichiganOnline/uux.aspx#/login
* https://miwam.unemployment.state.mi.us/mip/webdoc/_/#1

issues with firefox

**Comment by reepush** [comment]
https://www.namecheap.com/myaccount/login.aspx

wrong login field detection

**Comment by reepush** [comment]
https://p.turkishairlines.com/

login form not properly detected

**Comment by reepush** [comment]
@limpkin 
* https://www.myplanrs.com/tf/myPLAN/SponsorWelcome
Service isn't available. Because of my IP address?

* https://secure.linkpt.net/lpc/servlet/LPCLogin
There are 3 fields in form (store name, user id and password). Do we support this kind of forms?

* https://secure.mercbank.com/MercantileBankofMichiganOnline/uux.aspx#/login
Form and submit button were detected correctly. Can't find possible issue.

* https://miwam.unemployment.state.mi.us/mip/webdoc/_/#1
The main problem here is that password field is replaced when we focus input. I added input type to hash and extended password selector for mixed combination to handle it.

* https://www.namecheap.com/myaccount/login.aspx
Extending selector for mixed combination worked for this case.

* https://p.turkishairlines.com/
Updated `IGNORE_PATTERNS` for sign up button.

**Comment by limpkin** [comment]
@reepush 

1) I also get an error... may be temporary
2) we don't
3) ok
4) ok
5) cool!
6) awesome!

**Comment by reepush** [comment]
* https://www.grammarly.com/signin
React input issue. Fixed in latest version.

* https://10.0.50.130:8834/
Issue with updated DOM. Detached fields were filled.

* https://mynas:7777/
Made pull request with removing validation.

* https://doodle.com/account
Fixed in ifram-ui.

* https://archive.org/
Problem caused by input field with name "action". Fixed in latest version.

* https://www.screwfix.com/checkout/?_requestid=275227
Unable to reproduce issue. Can't see that we detect wrong fields. But I didn't get a payment page because of fake card number.

* https://www.waschbaer.de/shop/
Wrong submit button detection. Fixed in latest version.

* https://www.vudu.com/movies/
Wrong submit button detection. Added new selector.

* http://www.tapeheads.net
Password was cleared by client code. We don't have such problem in latest version, our code is executed before submit event.

* http://www.videokarma.org/index.php
Password was cleared by client code. We don't have such problem in latest version, our code is executed before submit event.

* https://login.comcast.net/login?r=comcast.net
We don't do auto sumbit in both 1.1.89 and latest version.

**Comment by reepush** [comment]
* https://accounts.google.com/ServiceLogin/signinchooser?passive=1209600
We have a test case for google account. Can't understand the problem here.

* chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/http-auth.html?{"isProxy":...
We had some issues in the past with HTTP Auth. Currently can't get auth by the provided link.

* https://www.asimovs.com/my-account/login/
Fixed in latest version.

* https://id.docker.com/login
React issue. Fixed in latest. Also added triggering change event after filling generated password.

* https://cfspart.impots.gouv.fr/LoginMDP?op=c
Added tel type to combinations.

* https://member.neteller.com/account/index?signInSc=true
Fixed with iframes.

* https://login.live.com/login.srf?wa=wsignin1.0
Tested and credentials are saved.

* https://www.indiegogo.com/
We have test case for this site. Fixed problem with keydown submit detection.

* https://p.turkishairlines.com/
Fixed. We have a test case for this site.
