### ISSUE TITLE
Device does not recognize keyboard layout

### ISSUE THREAD

**Issue by guilhermesfc** [limpkin/mooltipass#526]
### When required, Mooltipass should type the stored password values according to the configured keyboard layout, but Mooltipass disregards the selected keyboard layout.

Using keyboard layout = 'po_PO', create a password with, for instance, the _**-**_ char.
Ask Mooltipass to type the password in notepad.
You will see that Mooltipass writes _**'**_, as if using a US keyboard.

### Operating System
- Windows 10

### Mooltipass Extension
- the chrome extension 1.4.0

### Mooltipass Application
- the chrome application 2.0.81

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

**Comment by limpkin** [comment]
Hello,
That is extremely surprising as it has been thoroughly tested by thousands of users. 
Could you try setting the keyboard layout again and typing the password again on another computer?

**Comment by limpkin** [comment]
hello,
any news on that issue?

**Comment by guilhermesfc** [comment]
Hi,

Just tested on my wife's computer.
Had the exact same issue. Do you want screenshots?

Thanks

**Comment by limpkin** [comment]
Could you try other characters to se if only - is the problem?

**Comment by guilhermesfc** [comment]
Tried other three chars: Ç~´  and they are no written to the screen when requested.

**Comment by limpkin** [comment]
Could you store 2 logins with the following 2 strings:
- !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ
- [\]^_`abcdefghijklmnopqrstuvwxyz{|}~°

and paste here what the mooltipass enters?

**Comment by guilhermesfc** [comment]
Add to split it in 4 sets:

!ª#$%/º)=(»,'.-0123456789Çç
;«:_"abcdefghijklmnopqrstuvwxyz
+´&?\abcdefghijklmnopqrstuv
wxyz*>`|

**Comment by limpkin** [comment]
wow... that's not even close.
Could you let us know the keyboard layout configured on your computer? where are you from?

**Comment by guilhermesfc** [comment]
Portuguese keyboard layout.
I'm from Portugal.

**Comment by limpkin** [comment]
that must be it... could you try the layout PO_BR?

**Comment by VinnyCordeiro** [comment]
> that must be it... could you try the layout PO_BR?

[pt_pt](https://upload.wikimedia.org/wikipedia/commons/2/2c/KB_Portuguese.svg) and [pt_br](https://upload.wikimedia.org/wikipedia/commons/1/17/KB_Portuguese_Brazil.svg) layouts are very different, and that also includes the fact that ABNT2 (pt_br) layout have an extra key in comparison to ISO layouts: the right shift is split, like the JIS layout.

**Comment by limpkin** [comment]
@guilhermesfc it seems i'll therefore need to generate a special firmware update for your device, which will implement correct portuguese support!

**Comment by guilhermesfc** [comment]
That would be good, given that I have also ordered one for my father for Christmas ;)

**Comment by limpkin** [comment]
cool! could you send us both your serial numbers to support[at]themooltipass[dot]com?

**Comment by guilhermesfc** [comment]
I sent it for one of the devices.
The other has not arrived yet.

Thank you

**Comment by limpkin** [comment]
keyboard layout has been generated for portugal.
