### ISSUE TITLE
Possibility to select 'submit' button on multi button form

### ISSUE THREAD

**Issue by bklier** [limpkin/mooltipass#528]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Possibility to select 'submit' button on saving new page (just like the existing possibility to select username and password field)

### Justification
On some pages there are buttons like 'login', 'reset form', or 'reset password'. Sometimes Mooltipass just uses the wrong button to submit the credentials which renders the device on some pages absolutely useless (and that's too bad because it's a brilliant piece of hardware!)

### Workarounds
none
8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello,
Thanks for reporting that problem! Did you also report the problematic page(s) using the link in the extension menu?
Thanks for reporting and the kind words!

**Comment by bklier** [comment]
Now it has been reported ;-)

**Comment by limpkin** [comment]
thanks a lot!
@reepush will take care of that one :)
