### ISSUE TITLE
Unclear update/reflash proceedure

### ISSUE THREAD

**Issue by Chirishman** [limpkin/mooltipass#529]
I was using my Mooltipass Mini a while ago when I first got it and have since forgotten my pin. I've got spare smart cards so I'm trying to reset it to factory and start over by reflashing it to the base image, however the documentation on how to do that seems lacking.

### Expected behavior
According to [mini_update_proc.md](https://github.com/limpkin/mooltipass/blob/master/mini_update_proc.md) the you are supposed to update you Mooltipass Mini by using the Chrome Plugin, opening the developer console and feeding an img file with a name following this pattern _updatefile_yourMiniUid_hexstring.img_ to the "Import Media Bundle" Dialog using the hexstring from the file name in the password field.

### Actual behavior

On the [releases page](https://github.com/limpkin/mooltipass/releases) a hex file is provided not an img file and its name does not match the pattern.

### Operating System
Windows 10

### Mooltipass Extension
Chrome extension

### Mooltipass Application
Chrome application

### Mooltipass Device
The Mooltipass Mini

**Comment by limpkin** [comment]
This update procedure is not intended at all to reset a mini to its factory settings (and it actually won't do that).
If you forgot your PIN for your cards, there's unfortunately no way to reset them (and it'd be quite scary if you could).

**Comment by Chirishman** [comment]
I'm not trying to reset them and recover anything, I'm trying to wipe the device and start over clean as if it was blank out of the box. If reflashing the firmware isn't the method to wipe the device clean then what is?

**Comment by limpkin** [comment]
Firmware updates are only to update the firmware and not erase its internal memory contents.
The only way to erase the old user is to do it through the "settings" menu on the device.

**Comment by Chirishman** [comment]
So if there is a user on the device that you can no longer open then it lives on the device forever? Taking up space? Even if you wanted to sell or give the device to someone else in future?

**Comment by limpkin** [comment]
that is correct. You wouldn't want anyone to erase the data on your device.
In any case, the data is encrypted on the device and not accessible to other users.

**Comment by Chirishman** [comment]
I don't consider someone erasing the data on my device as any larger of a risk than any other thing that they could do with it if they had physical access such as drop the device down a well. Not losing them forever is the job keeping backups.

There is a max user limit and a finite amount of total space on the device aren't there? This means that can never be reclaimed.

Also, why does [this doc](https://github.com/limpkin/mooltipass/blob/master/mini_update_proc.md) tell you to make a backup? Just in case you brick the device? Because if I'm understanding this right you would have to run that backup manually, once for each enrolled user before you could safely upgrade the firmware. If that's the case the documentation should mention that.

**Comment by limpkin** [comment]
We advise to make a backup in case the user bricks the device indeed. We'll amend the update guide accordingly
