### ISSUE TITLE
Mooltipass can't use AltGr and Shift combos with manual password input

### ISSUE THREAD

**Issue by StefanWeiberg** [limpkin/mooltipass#533]
### Expected behavior
When entering a password in manual mode (f. e. in bash or desktop login screens) the Mooltipass can input symbols like @, { or $.
### Actual behavior
When using f. e. en_UK, en_US or de_DE my Mooltipass Mini doesn't use Shift or AltGr for correct input of symbols. It only uses Shift for letters but not for symbols. Recognized pages with the Chrome Extension work just fine.
### Step by step guide to reproduce the problem
Go in a text editor or bash and use the Login menu of the Mooltipass with a password or login that contains symbols (f. e. a username with an @)
### Operating System
- Antergos and Kubuntu
### Mooltipass Extension
Mention if you are using either:
- the chrome extension: 1.4.0
### Mooltipass Application
Mention if you are using either:
- MooltiApp: 2.0.82
### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

**Comment by limpkin** [comment]
Hello there,
This feature has been **extensively** tested for the last 4 years.
Could you double check this problem on other computers?

**Comment by StefanWeiberg** [comment]
The problem is connected to newer versions of X sessions (X11, Mesa,...). On Arch and Tumbleweed the problem only exists in sessions with an X Window. As soon as I switch to a different TTY and don't use an X session it works fine. On older Kernel and X11 versions it does work (f. e. Kubuntu 17.10). The window manager doesn't matter (tested on KDE5, Gnome3 and XFCE4)

**Comment by limpkin** [comment]
Hello Stefan!


We've actually recently changed our USB related code to cope with that.
If you send me your unit's serial number in private I can send you a custom
firmware for you to confirm our fix. We will then deploy it to all users

**Comment by limpkin** [comment]
firmware update tested and ready to be deployed.
Will send an email to backers within a week.
