### ISSUE TITLE
Lock manager when user locks screen (config option)

### ISSUE THREAD

**Issue by juliandroid** [limpkin/mooltipass#537]
### Missing feature
Add an option to lock (ask for PIN) Password Manager when you lock your screen (needed for laptop/desktop, but might be useful with smartphones too).

### Justification
Although there is Screen Saver option in the app (which doesn't seem to work when you lock your screen /Ctrl+L/ in Gnome) I would expect, when you leave your place (with Password Manager connected via USB) and display locked, the device to ask again for PIN code for the next interaction.
The reason is that you probably leave your working place for awhile (maybe in a hurry) and you don't want to take the device with you and in the same time you don't want your passwords exposed.

### Workarounds
Right now you have to do both things:
Ctrl+L to lock your PC and then to Lock the device or disconnect it from the USB.

My system is Linux + Gnome 3.26.2, but that is similarly useful for Windows/Mac/Android/etc.

**Comment by juliandroid** [comment]
The other way around could be also useful - to lock your user (desktop) when you hit Lock on the device, while connected on USB (this could be an option too, not a default behavior).

**Comment by limpkin** [comment]
Hello!

We actually have the other way around implemented in the device (remove the card, it'll lock your work station): see our user manual.
The first way is possible but not yet implemented in moolticute : https://github.com/limpkin/mooltipass/tree/master/source_code/src/USB#0xd9-lock-device (ping @raoulh )

**Comment by juliandroid** [comment]
@limpkin Not sure why the ticket is closed? Are you saying that this feature is not needed and won't be implemented?

**Comment by limpkin** [comment]
@juliandroid I'm saying the feature (both ways) is already implemented inside the mini firmware.

**Comment by juliandroid** [comment]
Regarding the other thing - if I remove the smart card from the device it doesn't lock the PC/desktop (i.e. doesn't simulate the Ctrl+L functionality).

So, if this ticket is closed, no one will ever consider implementing this in the app?

**Comment by limpkin** [comment]
@juliandroid just to be clear, win+l is not valid in your case, you'd like ctrl+l?

**Comment by juliandroid** [comment]
Win+L..  not sure why I type Ctrl+L all the time :/ I'm referring to Screen Lock :)

**Comment by limpkin** [comment]
yes, we indeed have this feature. It is described in our user manual, page 20.

**Comment by juliandroid** [comment]
I've tried both mooltipass app and moolticute.
At least in Gnome, it doesn't work:
 - Locking with Win+L to make the device ask PIN next time NOR removing the smart card to lock the Screen/Desktop.
I've tried any combination that includes "Win + L" string in the options menu.

But, I admit I don't understand how that option works and when/what happen, since the name is "Lock Unlock Feature" and the documentation is not clear to me:

> The different options inside the Lock/Unlock Feature list allow you to specify if a login and/or
> password should be sent when unlocking your smart card. The Mooltipass Mini will then send a
> credential stored inside an ‘_unlock_’ service in your database, if present. You may also select which
> (if any) key press should be sent when removing the smartcard from the Mooltipass Mini, for
> example, to lock your computer.

Maybe what I expect is not the same..

**Comment by limpkin** [comment]
Hello,

You want that feature, right? 
https://www.youtube.com/watch?v=jbGhDQdZx0Q&feature=youtu.be

**Comment by juliandroid** [comment]
Yes and no.

The Yes part - that is a nice feature, but I didn't know how to create that "_unlock_" user... but I figured it out that I have manually to create that "service". Also I didn't expect to have the same "_unlock_" service in order just to lock the screen.

The No part - I want the opposite - to leave my device and smartcard on the desk for a minute, instead of grabbing the card/device every time I have to get out of the room even for a minute, so instinctively I hit Win+L button just to lock the screen/desktop, but the device is not locked, so if I leave the device on the desk, everyone could potentially use my password manager and login to every place where I have credentials stored inside my password manager!

So, what I really need is a way to lock the password manager when I hit Win+L, so I don't have to duplicate the effort to also click "Lock" menu/entry on the device.

**Comment by limpkin** [comment]
No part: this is not yet implemented, and will have to be implemented in moolticute, which is not on this repository.
@raoulh : how hard would it be to implement it?

**Comment by raoulh** [comment]
The No part: Then you can use the "Lock after xx minutes of inactivity" which would lock the mooltipass

**Comment by raoulh** [comment]
@limpkin hard :)

**Comment by raoulh** [comment]
It would seriously be better to just remove the card once you want to leave your computer instead of typing win+L.
And also configure the mooltipass to send that win+L when you eject the card. You would lock both your mooltipass and your computer

**Comment by juliandroid** [comment]
I really prefer not to mechanically amortize the card/device by pulling the card every 5 minutes...
But if it is near to impossible and not portable at all to capture system wide Screen Lock, like using something like for Gnome:

> dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'"
 
Then some poor man's workaround could be an option inside Moolticute, to also lock the screen (as that already works when you unplug the card) when you click "Lock" menu on the device. Thus you amortize "_only_" the mechanical wheel :/
