### ISSUE TITLE
Cannot download files from mooltipass

### ISSUE THREAD

**Issue by alanrick** [limpkin/mooltipass#542]
Use one of the two templates below and delete the rest. All issues not following a template will be directly closed.
We apologize in advance if we ever take <a href="https://hackernoon.com/why-i-havent-fixed-your-issue-yet-a24ab4bc0d55">too long</a> to resolve your issue. This is due to the fact that Mooltipass mostly is a contributor based project.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Download a file from moolticute to Windows.
### Actual behavior
Cannot download a file
Error message "Data Fetch Denied for 'dab'!
This is followed by the app displaying "The Moolticute deamon is not running."

### Step by step guide to reproduce the problem
1. Enter moolticute file management mode
2. Enter credentials on the mooltipass device
3. Select the file to download 
4. Export file to download
5. Specify directory and filename of target
Error message "Data Fetch Denied for 'dab'!
This is followed by the app displaying "The Moolticute deamon is not running."

### Operating System

- Windows 10 Home 
Version 1709

Other operating systems are not supported.

### Mooltipass Extension

none

### Mooltipass Application
Mention if you are using either:
Moolticute v0.11.4-beta

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello,

Thanks for the bug report! 
However, this is not the right repo for this bug report. Could you therefore open an issue there? 
https://github.com/mooltipass/moolticute

**Comment by limpkin** [comment]
tagging @raoulh

**Comment by alanrick** [comment]
Will do. Sorry, blind faith in google!
