### ISSUE TITLE
Mooltipass Mini does *never* fill credentials with chrome automatically.

### ISSUE THREAD

**Issue by cornelinux** [limpkin/mooltipass#553]
### Expected behavior

The Mooltipass is plugged in and unlocked. The chrome plugin is installed.
When surfing to a login page, the mooltipass should blink and ask, if you want to log in.

[This worked a few month ago and it got worse and worse and stopped working completely]

(Moolitpass Mini (v1.2 #1425)
(Chrome 65.0.3325.181)

### Actual behavior

The mooltipass does not blink and ask to login.
I am not sure, if the chrome app or the moolitpass cable is buggy.

*Once the chrome app claimed no device was attached. I had to change the cable. The connector on the PCB of the mooltipass does not hold the cable very tighly. I am not sure if this might be a hardware mis-design.*

Only manual login is possbile. Which is very annoying to scroll through all the credentials!

### Step by step guide to reproduce the problem

* Plugin Mooltipass. 
* Unlock.
* Surf to website, for which the mooltipass has the credentials.
* *nothing happens*
* Login with the mooltipass manually.

### Operating System
- Ubuntu 16.04 LTS
  
Other operating systems are not supported.

### Mooltipass Extension
- the chrome extension: 1.4.5

### Mooltipass Application
Mention if you are using either:
- the chrome application: 1.4.5
- MooltiApp: if using Windows or MacOS, you have the latest version. If using Linux, please update to the latest version (https://themooltipass.com/setup.php -> **missing**)

### Mooltipass Device
- The Mooltipass Mini

**Comment by limpkin** [comment]
Hello, 

That is extremely strange as it is the very standard setup.  
Could you remove the chrome application and install moolticute from our setup page?  

Thanks

**Comment by cornelinux** [comment]
I rebooted the machine and it works again.
In the past sometimes I had the feeling, that a restart of chrome helped - but not always. Now a rebooted seemed to help, for now.

I will uninstall the chrome application and install moolticute and observe, if this is more stable.

**Comment by limpkin** [comment]
thanks!

**Comment by cornelinux** [comment]
Well, I do not fell like this is resolved, to reboot the computer to have this working again :-/

**Comment by limpkin** [comment]
I'll leave it opened until you confirm moolticute solved the problem then.
If you still encounter the same problem, we recommend you to test on another computer.
We look forward to hearing from you!

**Comment by limpkin** [comment]
Hello!
Any news?

**Comment by cornelinux** [comment]
Yes. I ran the last view days tests with a new udev rule and the old chrome app. 

Old rule:

    KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="16d0", ATTRS{idProduct}=="09a0", MODE="0664", GROUP="plugdev"

New rule:

    # udev rules for allowing console user(s) and libusb access to Mooltipass Mini devices
    ACTION!="add|change", GOTO="mooltipass_end"

    # console user
    KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="16d0", ATTRS{idProduct}=="09a0", MODE="0660", SYMLINK+="mooltipass_keyboard", TAG+="uaccess"
    # libusb
    SUBSYSTEM=="usb", ATTRS{idVendor}=="16d0", ATTRS{idProduct}=="09a0", MODE="0660", SYMLINK+="mooltipass_device", TAG+="uaccess"

    LABEL="mooltipass_end"

At first it seems the problem was gone. But then I experienced the same errors again.

I will now check for moolticute.
But honestly, I am still not sure, if there could also be a hardware problem with the loose usb connector, I mentioned earlier. I will check for moolticute and provide updates!
Thanks a lot!

**Comment by cornelinux** [comment]
Could you please give a pointer, 

* what I have to remove (everything that is called chrome extension and chrome app?) and 
* what I need to install? (Build and install this https://github.com/mooltipass/moolticute?)

**Comment by limpkin** [comment]
Diagnosing a loose usb connector can be done by using the manual credential recall feature: if the mini can type your credential for you, then it is ok.

What you need to remove: chrome App and MooltiApp
What you need to install: moolticute from themooltipass.com/setup

**Comment by cornelinux** [comment]
There might be a misunderstanding.

The link themooltipass.com/setup does not send mit to moolticute.

**Comment by limpkin** [comment]
can you reach themooltipass.com ?

Here's the well-formatted github-friendly link: https://www.themooltipass.com/setup/

**Comment by cornelinux** [comment]
Yes.
"I am a chrome user" takes me to the place, where I should install the chrome extension.

"I use all browsers" takes me to the place, where I should choose, which extensions to install! 

![image](https://user-images.githubusercontent.com/1908620/38413254-6e0c6742-398b-11e8-8128-d6d45d6beea6.png)

Ok, now I understand - I need to also install a browser extensions in chrome - even with mooltipass.

**Comment by cornelinux** [comment]
Thanks! I installed the chrome extension and moolticute and will see, if the problem is gone.

**Comment by cornelinux** [comment]
Using moolticute seems to work fine. Thanks a lot!

**Comment by limpkin** [comment]
wondeful! thanks for letting us know!
