### ISSUE TITLE
Why hasn't this repo been moved to the Mooltipass organization like all of the others?

### ISSUE THREAD

**Issue by NoahAndrews** [limpkin/mooltipass#554]
It looks more "legitimate" that way, and it keeps everything organized together

**Comment by limpkin** [comment]
because we're in the process of stripping the core parts and moving them to individual repos in the organization.

**Comment by NoahAndrews** [comment]
The way I worded this sounded rude, sorry. I was tired last night. That's an awesome answer :)

**Comment by limpkin** [comment]
;) thanks!  
We're looking for contributors for our next generation device ;)
