### ISSUE TITLE
Slow down password entry.

### ISSUE THREAD

**Issue by sclarkso** [limpkin/mooltipass#555]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Change password entry speed
### Justification
Multiple times in the OSX Recovery (disk encryption password, firmware password) box and in login fields in android apps only PART of the password is entered.  I assume OSX is rate-limiting the input?  And maybe my android phone just couldn't keep up?  Either way, it would be a nice addition to either be able to set some passwords as being entered more slowly, or have an overall 'compatibility' setting that slowed down the password entry.

### Workarounds
For the OSX disk encryption issue I was able to get it to type it into the terminal, then I wrote it down, then entered it manually.  For the android issues, I just put it on the PC and put the password into a text document and enter it manually.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello,

We do have this feature.
Did you read our user manual? It can be enabled through moolticute

**Comment by sclarkso** [comment]
I just found it. Thanks! 

I'll see if it fixes my issues.
