### ISSUE TITLE
Import/Migration Feature

### ISSUE THREAD

**Issue by scott79** [limpkin/mooltipass#556]
#### Import/Migration Feature

Ability to easily migrate creds that are stored in browsers local db. Upon completion of migration, option to erase from browser db.

### Justification
Quicker usage
Easier adoption (It's easy with browser plugin)

### Workarounds
Manual entry

**Comment by limpkin** [comment]
- you may install moolticute from this link: https://mooltipass-tests.com/mc_betas/v0.19.1-testing/
- press ctrl-shift-f2 and you'll see the csv import feature :)

**Comment by scott79** [comment]
Thank You.
