### ISSUE TITLE
Text on the display turned by 180 degrees

### ISSUE THREAD

**Issue by cornelinux** [limpkin/mooltipass#561]
### Expected behavior

Have the text on the display aligned this way, that the wheel is on the right side.

### Actual behavior

The text on the display is aligned or turned this way, that the wheel is on the left side.

![20181125_104247](https://user-images.githubusercontent.com/1908620/48977730-65e8f680-f0a0-11e8-9f1b-c5f7d4070507.jpg)

### Step by step guide to reproduce the problem

Leave your 2 year daughter unattended and have her climb on your desk, dance on the keyboad and do unreproducable stuff.

I assume there is probably a not-by-me-found feature to turn the text be 180 degrees. But I do not know how and where.

### Operating System
Mention if you are using either:
- Debian Based Distribution, Ubuntu 16.04
  
### Mooltipass Extension
Mention if you are using either:
- the chrome extension: 1.6.2

### Mooltipass Application
Mention if you are using either:
- I am using moolticute 0.20.2

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

### Website support
Not  website related.

**Comment by limpkin** [comment]
Simply hold your device the right way up steadily and it'll come back to its original position.
Somehow this information isn't present in our user manual

**Comment by cornelinux** [comment]
Wow. That was simple. I was not aware that there is a position sensor in it. THanks a lot!
Keep up the good work.
