### ISSUE TITLE
Web extension consuming a lot of resources

### ISSUE THREAD

**Issue by joshp205** [limpkin/mooltipass#562]
### Expected behavior
Web browser plugin should not be using as many resources.

### Actual behavior
With the web browser plugin enabled my browser climbs to 100% CPU usage and consumes ~1.5GB of RAM. Having more than one tab open usually makes things become unresponsive.

### Step by step guide to reproduce the problem
Not sure about reproducibility but this happens on both my laptop and desktop. Using either Firefox or Chrome has the same results. I run both browsers in private/incognito mode only. Both utilize uBlock Origin. Firefox also has NoScript added to it.

Having Moolticute running didn't seem to make a difference. Additionally, having the Mooltipass plugged in did not seem to make a difference.

I'm wondering if maybe there is conflict between the Mooltipass extensions and disallowing javascript.

### Operating System
- Windows 10
- MacOS

### Mooltipass Extension
- Chrome extension: v1.6.8
- Firefox extension: v1.6.8

### Mooltipass Application
Latest Moolticute for Windows and MacOS.

### Mooltipass Device
Mooltipass Mini

### Website support
N/A

This is most likely related to #560. I just got my Mooltipass and have been testing it out today. Once I got my browsers set up with the extension they became very sluggish. So far the Mooltipass has been a really cool tool though! Thanks for all the hard work everyone has put into it.

**Comment by joshp205** [comment]
After messing around with it more today it seems the issue isn't happening anymore.

**Comment by limpkin** [comment]
thanks for the update! we tried replicating the issue on our side... without success :/

**Comment by joshp205** [comment]
@limpkin 
Just wanted to add another follow up. When I was first running the Mooltipass I had a few tabs of reddit open. They were all using the old design (old.reddit.com) and I think that's where the problem is. I'm able to reproduce this problem if I visit the site on the old design; however, the new design works without problems.
