### ISSUE TITLE
Couldn't save credentials, please contact the support with moolticute's log

### ISSUE THREAD

**Issue by cwaazywabbit** [limpkin/mooltipass#565]
### Expected behavior
Credentials are saved normally.

### Actual behavior
Credentials are not saved and lost. An error occurs "Couldn't save credentials, please contact the support with moolticute's log"

### Step by step guide to reproduce the problem
1. unlock device / use it to login to something and keep it unlocked
1. using Moolticute, open Credentials Management / confirm on device
1. start adding credentials / don't save to device
1. let the session timeout / Credential Management will auto lock the session
1. unlock the device again / Credentials Management will auto unlock in Moolticute
1. click to save credentials now / you receive the following error and new credentials are lost
"Couldn't save credentials, please contact the support with moolticute's log"

### Operating System
Windows 10

### Mooltipass Extension
None

### Mooltipass Application
Moolticute 0.42.1

### Mooltipass Device
The Mooltipass Mini

**Comment by cwaazywabbit** [comment]
Moved to the correct repo
https://github.com/mooltipass/moolticute/issues/456

**Comment by limpkin** [comment]
Hello!

That's quite a corner case... Could you let us know in your opinion what
justifies letting the session timeout? This is something we left as is
thinking this would rarely happen.
As far as I know you are the first one to bring it up.
