### ISSUE TITLE
Description field is limited to 22 chars

### ISSUE THREAD

**Issue by cwaazywabbit** [limpkin/mooltipass#566]
### Expected behavior
Description field isn't limited or at least not limited to this very small length

### Actual behavior
Description field is limited to 22 characters only!

### Step by step guide to reproduce the problem
Try to enter any description in Moolticute for a record

### Operating System
Windows 10

### Mooltipass Extension
None

### Mooltipass Application
Moolticute 0.42.1

### Mooltipass Device
The Mooltipass Mini

**Comment by cwaazywabbit** [comment]
Moved to correct repo
https://github.com/mooltipass/moolticute/issues/457

**Comment by limpkin** [comment]
This is per design, and the first time this is brought up... How many would
you like?
