### ISSUE TITLE
Moolticute App does not start on screens with higher resolution

### ISSUE THREAD

**Issue by new-gen23** [limpkin/mooltipass#569]
### Expected behavior
Moolticute App should start under Ubuntu

### Actual behavior
The application starts after 5 minutes but the inside of the QT window remains blank

### Step by step guide to reproduce the problem
I follow to download installation für ubuntu from the website (apt add repo, apt update, apt install ...)
Then I start "moolticute" from the console.
My current screen resolution is 5120x1440. When I start the application, it takes about 3 minutes to open the window. Then the QT window is maximized (cannot resize it) and it remains mostly blank.
When I configure my screen resolution to a lower value (1920x1080) before starting the app, the application runs normally. If I switch the resolution back to 5120x1440, the app continues to work.

I would assume that it's a QT problem, as my VLC experiences a similar problem. 

### Operating System
Mention if you are using either:
- Ubuntu 18.04

### Mooltipass Extension
Mention if you are using either:
- none

### Mooltipass Application
Mention if you are using either:
- MooltiApp

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

**Comment by limpkin** [comment]
hello!
Thanks for reporting this issue! Unfortunately, this is the wrong repo... please use https://github.com/mooltipass/moolticute
