### ISSUE TITLE
Moolticute Daemon seems not to run, preventing the manager to contact the device

### ISSUE THREAD

**Issue by new-gen23** [limpkin/mooltipass#570]
### Expected behavior
Moolticute Deamon should start, so Moolticute App can be used

### Actual behavior
Daemon does not start.

### Step by step guide to reproduce the problem
I installed the app using the manual for Ubuntu. 
The application starts but tells me that the Moolticute-Daemon is not running. I right click on the icon in the taskbar and select "Daemon neu starten". This brings up the following messages in the console:
WARNING: :0 - Daemon exits with error code  9  Exit Status :  QProcess::ExitStatus(CrashExit)
INFO: :0 - Daemon started 

However, the application is still stuck at the point that the daemon is not reachable. Further errors are visible:
DEBUG: :0 - Websocket disconnect
DEBUG: :0 - Websocket error:  "No websocket object"
DEBUG: :0 - Websocket open()
DEBUG: :0 - Websocket open()
DEBUG: :0 - Websocket disconnect
DEBUG: :0 - Websocket error:  "No websocket object"

### Operating System
- Ubuntu 18.04  
Other operating systems are not supported.

### Mooltipass Extension
- none

### Mooltipass Application
- MooltiApp

### Mooltipass Device
- The Mooltipass Mini

**Comment by limpkin** [comment]
hello!
Thanks for reporting this issue! Unfortunately, this is the wrong repo... please use https://github.com/mooltipass/moolticute
