### ISSUE TITLE
Feature Request: Moolticute Gui cannot be accessed if started in background. Provide a foreground parameter.

### ISSUE THREAD

**Issue by new-gen23** [limpkin/mooltipass#572]
### Expected behavior
Run Moolticute-v0.44.0-x86_64.AppImage -f
-f = foreground 

### Actual behavior
cannot use the app because I cannot fix the stupid linux bug. Sorry, it's not your fault, i know.

### Operating System
Linux <host> 5.6.0-1017-oem #17-Ubuntu SMP Tue Jun 23 18:59:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Mooltipass Extension
none

### Mooltipass Application
Moolticute Gui Version 0.44.0 and earlier

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

**Comment by limpkin** [comment]
hello!
That's the wrong repo to file this issue... could you file it at https://github.com/mooltipass/moolticute ?
