### ISSUE TITLE
Unable to install on corporate windows machine due to defender and the signatures on your app

### ISSUE THREAD

**Issue by JessicaMulein** [limpkin/mooltipass#574]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Proper dev/store/app credentials

### Justification
The Mini BLE will not be usable for a great many users.

### Workarounds

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello!
I'm confused... are you using moolticute? if so it should work right out of the box :)

**Comment by JessicaMulein** [comment]
My apologies. In anticipation of my Mini BLE I started downloading your extensions, etc so I could start familiarizing. I tried to install the desktop app component on my windows domain joined machine and was told it was not from a trusted developer or something to that extent. Perhaps there's a step I missed. I'll look on my next break!

**Comment by limpkin** [comment]
ok 👍 
have a look at themooltipass.com/setup :)

**Comment by JessicaMulein** [comment]
![Screenshot 2020-12-17 022221](https://user-images.githubusercontent.com/3766240/102475491-c728ed00-400e-11eb-9ae8-b790e561ae3b.jpg)
