### ISSUE TITLE
Autodetect keyboard layout

### ISSUE THREAD

**Issue by kisst** [limpkin/mooltipass#580]
### Missing feature
The App on OS level should be able to detect the current Keyboard layout setting, and communicate this with the HW device, which can then send input with that taken into consideration.

### Justification
Seamless easy to use experience, no mistyped password due to layout issues. 

### Workarounds
Do it by hand and check the layout every time.

**Comment by limpkin** [comment]
this is the wrong repo for this issue (should be mooltipass/minible).
On moolticute you have a way to "force" the layout that the device uses so whenever the mini ble is connected to that computer it'll use that particular layout.
