### ISSUE TITLE
Installation error Ubuntu 21.10

### ISSUE THREAD

**Issue by archie-chess** [limpkin/mooltipass#581]
8<------------------------ BUG REPORT -----------------------------------------
### ExpecteId behavior
Installation using following commands:

In a terminal, type the following commands:
sudo add-apt-repository ppa:mooltipass/moolticute
sudo apt-get update
sudo apt-get install moolticute 

### Actual behavior

$ sudo add-apt-repository ppa:mooltipass/moolticute
Repository: 'deb http://ppa.launchpad.net/mooltipass/moolticute/ubuntu/ impish main'
Description:
Packages for Moolticute.

This project aims to be an easy companion to your Mooltipass device and extend the power of the device to more platform/tools. With it you can manage your Mooltipass with a cross platform app, as well as provide a daemon service that handle all USB communication with the device.

For questions and bugs please contact https://github.com/mooltipass/moolticute/issues/new
More info: https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/mooltipass-ubuntu-moolticute-impish.list
Adding deb entry to /etc/apt/sources.list.d/mooltipass-ubuntu-moolticute-impish.list
Found existing deb-src entry in /etc/apt/sources.list.d/mooltipass-ubuntu-moolticute-impish.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/mooltipass-ubuntu-moolticute-impish.list
Adding key to /etc/apt/trusted.gpg.d/mooltipass-ubuntu-moolticute.gpg with fingerprint 05452CC8203FE171D20B4F91D30397520E0A5FDD
Get:1 http://security.ubuntu.com/ubuntu impish-security InRelease [110 kB]
Ign:2 http://ppa.launchpad.net/mooltipass/moolticute/ubuntu impish InRelease                                                    
Hit:3 http://nl.archive.ubuntu.com/ubuntu impish InRelease                                                                      
Hit:4 https://updates.signal.org/desktop/apt xenial InRelease                                                                         
Hit:5 http://nl.archive.ubuntu.com/ubuntu impish-updates InRelease                                                                    
Err:6 http://ppa.launchpad.net/mooltipass/moolticute/ubuntu impish Release     
  404  Not Found [IP: 91.189.95.85 80]
Hit:7 http://nl.archive.ubuntu.com/ubuntu impish-backports InRelease                      
Reading package lists... Done                           
E: The repository 'http://ppa.launchpad.net/mooltipass/moolticute/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Step by step guide to reproduce the problem
see above step
### Operating System
Mention if you are using either:

- Debian Based Distribution

  Ubuntu 21.10

### Mooltipass Device

- The Mooltipass Mini ble but irrelevant

### Website support
If your issue is related to website support, please use the "Report incompatibilities with this website" item in the extension menu. You may still use a GitHub issue if you notice a major bug that impacts multiple websites at once.

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
wrong repository: https://github.com/mooltipass/moolticute

At the moment, 21.10 release is only available on our beta channel: https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute-beta
