### ISSUE TITLE
keycode inconsistent behavior

### ISSUE THREAD

**Issue by oriansj-som** [limpkin/mooltipass#582]
<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
keycodes sent to Windows and Linux systems match with current generation mooltipass mini ble as it did in the old mooltipass mini

### Actual behavior
After selecting US keymap on linux > character is inserted instead of the correct | character
After selecting US Intl keymap on linux `\x20 is inserted instead of just `
After selecting US MacOS keymap | is inserted instead of < character
(probably more but this is the ones found initially)

### Step by step guide to reproduce the problem
create a password with the above characters using the latest moolticute on a stock Redhat/Debian/Ubuntu desktop
open a text editor on linux and have the mooltipass ble type the password (notice the changed output)
open a text editor on Windows and have mooltipass ble type the password (notice it doesn't match)

### Operating System
- Windows 10
- Redhat/Debian/Ubuntu
  
### Mooltipass Extension
Just straight using mooltipass ble as a keyboard with no additional software installed

### Mooltipass Application
Moolticute is used for the entering of the password(s) and importing to the various different devices

### Mooltipass Device
The Mooltipass Mini (Works correctly)
The Mooltipass Mini BLE (Has the behavior)

### Website support
Host Os keyboard behavior only

<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
I'm thinking this should be better filed at https://github.com/mooltipass/minible :)
However, unless i'm mistaken, since bundle v8 we do have a "Ubuntu" layout... could you try it?
